-- =====================================================================
-- 20260625000010_seed_real.sql  —  Module G real seed dataset (STAGED)
-- GENERATED from /data/*.csv by /data/build_seed_sql.py. Do not hand-edit;
-- edit the CSVs (the reviewable source of truth) and regenerate.
--
-- Idempotent + supersedes the Phase-0 demo seed (...000003) via
-- INSERT ... ON CONFLICT (<natural key>) DO UPDATE. Safe to re-run.
-- Natural keys: colors.id | fibers/plants/phytochemicals.name |
--   districts.order | guilds.internal_name | foods.canonical_name |
--   junctions composite PK.
--
-- 🔒 FENCE 2 (SPEC §14): guilds.claim_risk=true on Mood/Estrogen/Mitochondria/
--   Tumor names; substantiation is RD-REVIEW-REQUIRED placeholder copy.
-- 🔒 FENCE 4 (SPEC §14): food_fibers.est_grams_per_serving values are COARSE
--   placeholders. Never surface as measured grams.
-- Sources cited per-file in /data/*.csv (USDA FoodData Central; USDA flavonoid
--   tables; Phenol-Explorer; framework §4-5).
-- Supabase applies each migration file inside its own transaction, so this
-- file omits an explicit BEGIN/COMMIT (matches the repo's other migrations).
-- =====================================================================

-- ---- colors (rainbow groups) — ON CONFLICT (id) ----------------------
insert into colors (id, meaning_copy, what_it_does_copy) values
  ('red', 'Lycopene, anthocyanins and ellagic acid', 'Polyphenols linked to heart and circulation; some feed mucus-barrier crews'),
  ('orange', 'Alpha- and beta-carotene', 'Carotenoids the body can turn into vitamin A for eyes, skin and immune signalling'),
  ('yellow', 'Flavonoids, lutein and zeaxanthin', 'A broad antioxidant mix; lutein and zeaxanthin concentrate in the eye'),
  ('green', 'Chlorophyll, folate and lutein', 'Folate supports methylation; chlorophyll and glucosinolates ride along in leafy and cruciferous greens'),
  ('blue_purple', 'Anthocyanins', 'Deep-pigment polyphenols that reach the colon and feed barrier-keeping bacteria like Akkermansia'),
  ('white_brown', 'Organosulfur compounds and quercetin', 'Allium sulfur compounds and prebiotic fibers; the fuel layer for your Base Layer bifidobacteria')
on conflict (id) do update set
  meaning_copy = excluded.meaning_copy,
  what_it_does_copy = excluded.what_it_does_copy;

-- ---- fibers — ON CONFLICT (name) -------------------------------------
insert into fibers (name, is_fodmap_trigger, fermentability, solubility, notes) values
  ('inulin', true, 'high', 'soluble', 'Fructan. Top bacterial fuel AND classic IBS trigger. Chicory, jerusalem artichoke, onion, garlic.'),
  ('fos', true, 'high', 'soluble', 'Fructo-oligosaccharide; shorter-chain fructan, distinct from inulin. Onion, garlic, asparagus.'),
  ('gos', true, 'high', 'soluble', 'Galacto-oligosaccharide. Legumes and some dairy. A FODMAP trigger.'),
  ('rs2', false, 'moderate', 'resistant', 'Resistant starch, native granular form. Green banana, raw potato starch, legumes.'),
  ('rs3', false, 'moderate', 'resistant', 'Retrograded resistant starch, formed when cooked starch is cooled. Cooled rice and potato.'),
  ('pectin', false, 'moderate', 'soluble', 'Soluble, gentle, gel-forming. Apple, citrus, carrot. Feeds butyrate producers.'),
  ('beta_glucan', false, 'moderate', 'soluble', 'Soluble fiber of oats, barley and mushrooms. Feeds propionate producers; lowers cholesterol.'),
  ('arabinoxylan', false, 'moderate', 'insoluble', 'Major fiber of whole wheat, rye and bran. Commonly overlooked; feeds Base Layer and Appetite Crew.'),
  ('psyllium', false, 'low', 'soluble', 'Husk fiber. Poorly fermented, so it bulks mechanically rather than feeding much.'),
  ('mucilage', false, 'moderate', 'soluble', 'Gel fiber of chia, flax and okra. Fermentable; soothes and feeds butyrate producers.')
on conflict (name) do update set
  is_fodmap_trigger = excluded.is_fodmap_trigger,
  fermentability = excluded.fermentability,
  solubility = excluded.solubility,
  notes = excluded.notes;

-- ---- phytochemicals — ON CONFLICT (name); maps_to_color after colors -
insert into phytochemicals (name, class, maps_to_color_id) values
  ('allicin', 'organosulfur'::phyto_class, 'white_brown'::color_name),
  ('alpha_carotene', 'carotenoid'::phyto_class, 'orange'::color_name),
  ('alpha_pinene', 'terpene'::phyto_class, 'green'::color_name),
  ('anthocyanin', 'polyphenol'::phyto_class, 'blue_purple'::color_name),
  ('asparagoside', 'saponin'::phyto_class, 'green'::color_name),
  ('avenacoside', 'saponin'::phyto_class, 'white_brown'::color_name),
  ('avenasterol', 'phytosterol'::phyto_class, 'white_brown'::color_name),
  ('beta_carotene', 'carotenoid'::phyto_class, 'orange'::color_name),
  ('beta_cryptoxanthin', 'carotenoid'::phyto_class, 'orange'::color_name),
  ('beta_sitosterol', 'phytosterol'::phyto_class, 'white_brown'::color_name),
  ('betanidin', 'betalain'::phyto_class, 'red'::color_name),
  ('betanin', 'betalain'::phyto_class, 'red'::color_name),
  ('brassicasterol', 'phytosterol'::phyto_class, 'green'::color_name),
  ('caffeine', 'alkaloid'::phyto_class, 'green'::color_name),
  ('campesterol', 'phytosterol'::phyto_class, 'white_brown'::color_name),
  ('capsaicin', 'alkaloid'::phyto_class, 'red'::color_name),
  ('carnosic_acid', 'terpene'::phyto_class, 'green'::color_name),
  ('catechin', 'polyphenol'::phyto_class, 'green'::color_name),
  ('chavicine', 'alkaloid'::phyto_class, 'white_brown'::color_name),
  ('chickpea_saponin', 'saponin'::phyto_class, 'white_brown'::color_name),
  ('chlorogenic_acid', 'polyphenol'::phyto_class, 'white_brown'::color_name),
  ('chlorophyll', 'chlorophyll'::phyto_class, 'green'::color_name),
  ('chlorophyll_a', 'chlorophyll'::phyto_class, 'green'::color_name),
  ('chlorophyll_b', 'chlorophyll'::phyto_class, 'green'::color_name),
  ('chlorophyllin', 'chlorophyll'::phyto_class, 'green'::color_name),
  ('curcumin', 'polyphenol'::phyto_class, 'yellow'::color_name),
  ('diallyl_disulfide', 'organosulfur'::phyto_class, 'white_brown'::color_name),
  ('ellagic_acid', 'polyphenol'::phyto_class, 'red'::color_name),
  ('epigallocatechin_gallate', 'polyphenol'::phyto_class, 'green'::color_name),
  ('eugenol', 'terpene'::phyto_class, 'white_brown'::color_name),
  ('genistein', 'polyphenol'::phyto_class, 'white_brown'::color_name),
  ('glucosinolate', 'organosulfur'::phyto_class, 'green'::color_name),
  ('hesperidin', 'polyphenol'::phyto_class, 'orange'::color_name),
  ('indicaxanthin', 'betalain'::phyto_class, 'yellow'::color_name),
  ('isobetanin', 'betalain'::phyto_class, 'red'::color_name),
  ('kaempferol', 'polyphenol'::phyto_class, 'yellow'::color_name),
  ('limonene', 'terpene'::phyto_class, 'orange'::color_name),
  ('linalool', 'terpene'::phyto_class, 'green'::color_name),
  ('lutein', 'carotenoid'::phyto_class, 'green'::color_name),
  ('lycopene', 'carotenoid'::phyto_class, 'red'::color_name),
  ('menthol', 'terpene'::phyto_class, 'green'::color_name),
  ('naringenin', 'polyphenol'::phyto_class, 'yellow'::color_name),
  ('pheophytin', 'chlorophyll'::phyto_class, 'green'::color_name),
  ('piperine', 'alkaloid'::phyto_class, 'white_brown'::color_name),
  ('punicalagin', 'polyphenol'::phyto_class, 'red'::color_name),
  ('quercetin', 'polyphenol'::phyto_class, 'yellow'::color_name),
  ('quinoa_saponin', 'saponin'::phyto_class, 'white_brown'::color_name),
  ('resveratrol', 'polyphenol'::phyto_class, 'blue_purple'::color_name),
  ('s_allyl_cysteine', 'organosulfur'::phyto_class, 'white_brown'::color_name),
  ('secoisolariciresinol', 'polyphenol'::phyto_class, 'white_brown'::color_name),
  ('solanine', 'alkaloid'::phyto_class, 'blue_purple'::color_name),
  ('soyasaponin', 'saponin'::phyto_class, 'white_brown'::color_name),
  ('stigmasterol', 'phytosterol'::phyto_class, 'white_brown'::color_name),
  ('sulforaphane', 'organosulfur'::phyto_class, 'green'::color_name),
  ('vulgaxanthin', 'betalain'::phyto_class, 'yellow'::color_name),
  ('zeaxanthin', 'carotenoid'::phyto_class, 'yellow'::color_name)
on conflict (name) do update set
  class = excluded.class,
  maps_to_color_id = excluded.maps_to_color_id;

-- ---- districts — update-then-insert (order is unique per world now) --
update districts d set name = v.name, unlock_rule_key = v.unlock_rule_key
from (values
  (1, 'The Backbone District', 'tier2_unlocked'),
  (2, 'The Keystones', 'two_backbone_blooming'),
  (3, 'The Scientists', 'one_keystone_blooming_and_10_days'),
  (4, 'The Hidden Gems', 'after_d3_engagement')
) as v("order", name, unlock_rule_key)
where d."order" = v."order";
insert into districts ("order", name, unlock_rule_key)
select * from (values
  (1, 'The Backbone District', 'tier2_unlocked'),
  (2, 'The Keystones', 'two_backbone_blooming'),
  (3, 'The Scientists', 'one_keystone_blooming_and_10_days'),
  (4, 'The Hidden Gems', 'after_d3_engagement')
) as v("order", name, unlock_rule_key)
where not exists (select 1 from districts d where d."order" = v."order");

-- ---- guilds — ON CONFLICT (internal_name); Fence 2 claim_risk -------
insert into guilds (district_id, internal_name, display_name, function_copy, confidence_tag, feeds_copy, claim_risk, substantiation)
select d.id, v.internal_name, v.display_name, v.function_copy, v.confidence_tag::confidence_tag, v.feeds_copy, v.claim_risk, v.substantiation
from (values
  (1, 'anti_inflammatory_arsenal', 'The Anti-inflammatory Arsenal', 'Butyrate producers (Faecalibacterium, Roseburia) that fuel the gut lining and calm inflammation. The backbone.', 'solid', 'Resistant starch, pectin, beta-glucan, oats and beans', false, null),
  (1, 'appetite_crew', 'The Appetite Crew', 'Propionate producers (Bacteroides) tied to satiety, steadier blood sugar and lower cholesterol.', 'solid', 'Beta-glucan, barley, arabinoxylan and seaweed', false, null),
  (1, 'base_layer', 'The Base Layer', 'Bifidobacteria that acidify the gut, crowd out pathogens and feed everyone else. Base of the pyramid.', 'solid', 'Inulin, FOS and GOS, onion, garlic, chicory and legumes', false, null),
  (1, 'recycling_engine', 'The Recycling Engine', 'Lactate utilizers (Anaerostipes, E. hallii) that turn lactate into more butyrate and keep the system stable.', 'solid', 'Indirect, they eat what the Base Layer makes, so feed the Base Layer', false, null),
  (2, 'locksmith', 'The Locksmith', 'Ruminococcus bromii, cracks open resistant-starch particles so everyone else can feed. Without it, RS passes straight through.', 'solid', 'Resistant starch, green banana, cooled rice and potato', false, null),
  (2, 'knights_of_the_wall', 'The Knights of the Wall', 'Akkermansia muciniphila, maintains the mucus barrier and tracks with metabolic health.', 'maturing', 'Polyphenols, cranberry, pomegranate, green tea and concord grape', false, null),
  (3, 'vitamin_lab', 'The Vitamin Lab', 'Vitamin synthesizers that produce K2, folate, biotin and B12. Where your 30-plants number cashes out into a mechanism.', 'solid', 'Overall diversity, the wider your plant range, the busier this lab', false, null),
  (3, 'mood_regulators', 'The Mood Regulators', 'Tryptophan and indole producers on the gut-brain axis; ties to the mood dashboard.', 'frontier', 'Tryptophan-rich foods (oats, seeds, soy) plus fiber', true, '[emerging science] RD-REVIEW-REQUIRED: gut-brain axis is a real and active research field, but a direct food→mood causal claim is unproven in humans. Frame as association only; never imply the app treats mood. Pending RD sign-off.'),
  (4, 'estrogen_regulators', 'The Estrogen Regulators', 'Equol producers from soy isoflavones; roughly 1 in 3 people host them. Equol is a potent phytoestrogen of cardiovascular, bone and menopause interest.', 'emerging', 'Soy isoflavones, soybean, tempeh, tofu and miso', true, '[emerging science] RD-REVIEW-REQUIRED: equol-producer status is a real metabotype confirmed only by a urine test after a soy challenge, not by tracking intake. Phytoestrogen health effects are emerging, not established. No therapeutic claim. Pending RD sign-off.'),
  (4, 'mitochondria_boosters', 'The Mitochondria Boosters', 'Urolithin producers from ellagitannins; metabotypes A/B/0. Urolithin A is studied for mitochondrial and muscle health.', 'emerging', 'Pomegranate, walnuts and berries', true, '[emerging science] RD-REVIEW-REQUIRED: urolithin-A benefits rest on early human trials and supplement studies, not whole-food outcomes. Producer status is a metabotype, not guaranteed by intake. No therapeutic claim. Pending RD sign-off.'),
  (4, 'tumor_preventors', 'The Tumor Preventors', 'Enterolignan producers from plant lignans; enterolactone is of hormonal and cardiovascular interest.', 'associational', 'Flax, sesame and rye', true, '[emerging science] RD-REVIEW-REQUIRED: ASSOCIATIONAL ONLY, NOT proven cancer prevention. Cancer-prevention claims are heavily scrutinized by FDA/FTC and app-store review. Name is placeholder; likely must be softened before launch. Pending RD sign-off.'),
  (4, 'stone_breakers', 'The Stone Breakers', 'Oxalate degraders (Oxalobacter), niche, but a clean food→function link that matters mainly for kidney-stone formers.', 'solid', 'Niche, they process oxalate from foods like spinach, beet and almond', false, null)
) as v(district_order, internal_name, display_name, function_copy, confidence_tag, feeds_copy, claim_risk, substantiation)
join districts d on d."order" = v.district_order
on conflict (internal_name) do update set
  district_id = excluded.district_id,
  display_name = excluded.display_name,
  function_copy = excluded.function_copy,
  confidence_tag = excluded.confidence_tag,
  feeds_copy = excluded.feeds_copy,
  claim_risk = excluded.claim_risk,
  substantiation = excluded.substantiation;

-- ---- plants — ON CONFLICT (name); description = field-guide blurb ----
insert into plants (name, scientific_name, plant_family, rarity_tier, description) values
  ('Almond', 'Prunus dulcis', 'Rosaceae', 'uncommon', 'The skins carry polyphenols and the flesh carries fiber — a handful feeds more than you.'),
  ('Apple', 'Malus domestica', 'Rosaceae', 'common', 'Pectin in the flesh, quercetin in the peel — the original portable prebiotic.'),
  ('Artichoke', 'Cynara cardunculus var. scolymus', 'Asteraceae', 'rare', 'Cynarin plus serious inulin — the fanciest prebiotic on the plate.'),
  ('Arugula', 'Eruca vesicaria', 'Brassicaceae', 'uncommon', 'The peppery bite IS the phytochemicals — erucin and friends, straight from the leaf.'),
  ('Asparagus', 'Asparagus officinalis', 'Asparagaceae', 'uncommon', 'Spring''s prebiotic spear — fructans plus glutathione in a five-minute cook.'),
  ('Avocado', 'Persea americana', 'Lauraceae', 'uncommon', 'A fruit that eats like a fat — with more fiber per half than most salads.'),
  ('Banana', 'Musa acuminata', 'Musaceae', 'common', 'Ripe and sweet feeds you; the greener it is, the more it feeds your microbes.'),
  ('Barley', 'Hordeum vulgare', 'Poaceae', 'uncommon', 'Chewy, nutty, and even richer in beta-glucan than oats — soup''s best upgrade.'),
  ('Basil', 'Ocimum basilicum', 'Lamiaceae', 'common', 'A handful of leaves is a legitimate plant — rosmarinic acid rides in the aroma.'),
  ('Beet', 'Beta vulgaris', 'Amaranthaceae', 'uncommon', 'Betalains stain everything for a reason — pigment IS the payload. Roast, grate, or pickle.'),
  ('Bell pepper', 'Capsicum annuum', 'Solanaceae', 'common', 'One plant, three colors — red, yellow, and green peppers each lean into different carotenoids.'),
  ('Black bean', 'Phaseolus vulgaris', 'Fabaceae', 'uncommon', 'Dark skins mean anthocyanin cousins — pigment and fiber in the same spoonful.'),
  ('Black pepper', 'Piper nigrum', 'Piperaceae', 'common', 'Piperine — the everyday grind that helps other compounds (curcumin!) absorb.'),
  ('Blackberry', 'Rubus fruticosus', 'Rosaceae', 'uncommon', 'So purple it''s nearly black — that depth is anthocyanin density.'),
  ('Blueberry', 'Vaccinium corymbosum', 'Ericaceae', 'uncommon', 'Anthocyanins by the cupful — the berry your barrier-guarding crews adore.'),
  ('Bok choy', 'Brassica rapa subsp. chinensis', 'Brassicaceae', 'uncommon', 'A crucifer that cooks in minutes — crisp stems, tender greens, stir-fry''s favorite vehicle.'),
  ('Brazil nut', 'Bertholletia excelsa', 'Lecythidaceae', 'rare', 'One or two a day covers selenium — a rare find that asks for restraint, not volume.'),
  ('Broccoli', 'Brassica oleracea var. italica', 'Brassicaceae', 'common', 'The famous one: sulforaphane''s parent compound lives in these florets. Steam it lightly, chew it well.'),
  ('Brown rice', 'Oryza sativa', 'Poaceae', 'common', 'The bran layer is the point — and cooled leftover rice picks up resistant starch.'),
  ('Brussels sprouts', 'Brassica oleracea var. gemmifera', 'Brassicaceae', 'uncommon', 'Tiny cabbages with an outsized glucosinolate load. Roasting converts the skeptics.'),
  ('Buckwheat', 'Fagopyrum esculentum', 'Polygonaceae', 'rare', 'No wheat, no gluten — rutin-rich seeds that make noodles and pancakes.'),
  ('Butternut squash', 'Cucurbita moschata', 'Cucurbitaceae', 'uncommon', 'Sweet orange flesh that carries beta-carotene through soups and roasts all winter.'),
  ('Cabbage', 'Brassica oleracea var. capitata', 'Brassicaceae', 'common', 'Cheap, keeps for weeks, and ferments into kimchi and sauerkraut — the most versatile crucifer in the guide.'),
  ('Carrot', 'Daucus carota', 'Apiaceae', 'common', 'Beta-carotene''s poster child, plus pectin — a gentle fiber your butyrate-makers appreciate.'),
  ('Cashew', 'Anacardium occidentale', 'Anacardiaceae', 'uncommon', 'Creamy enough to become sauce — a softer entry into daily nuts.'),
  ('Cauliflower', 'Brassica oleracea var. botrytis', 'Brassicaceae', 'common', 'A white-brown crucifer that roasts into sweetness — same glucosinolate family as broccoli, different fiber mix.'),
  ('Celery', 'Apium graveolens', 'Apiaceae', 'common', 'The quiet base of a thousand soups — apigenin and crunch, cheap diversity.'),
  ('Chia seed', 'Salvia hispanica', 'Lamiaceae', 'uncommon', 'The gel is the fiber — mucilage that turns pudding-like and feeds gently.'),
  ('Chickpea', 'Cicer arietinum', 'Fabaceae', 'uncommon', 'GOS-rich and endlessly flexible — hummus, roasted, or straight into the stew.'),
  ('Chicory root', 'Cichorium intybus', 'Asteraceae', 'legendary', 'Where supplement-bottle inulin actually comes from — the deepest prebiotic cut in the guide.'),
  ('Chili pepper', 'Capsicum annuum var. glabriusculum', 'Solanaceae', 'uncommon', 'Capsaicin is the point — a little heat is a phytochemical dose.'),
  ('Chives', 'Allium schoenoprasum', 'Amaryllidaceae', 'uncommon', 'A sprinkle counts — the smallest allium still brings organosulfur compounds to the plate.'),
  ('Cilantro', 'Coriandrum sativum', 'Apiaceae', 'common', 'Love-it-or-soap — either way its leaf carries genuine phytochemical weight.'),
  ('Cinnamon', 'Cinnamomum verum', 'Lauraceae', 'uncommon', 'Tree bark, technically — proanthocyanidins in dessert''s favorite spice.'),
  ('Collard greens', 'Brassica oleracea var. viridis', 'Brassicaceae', 'uncommon', 'The sturdy southern crucifer — slow-cooked or raw as a wrap, fiber either way.'),
  ('Concord grape', 'Vitis labrusca', 'Vitaceae', 'rare', 'The deep-purple American grape — juice-dark skins loaded with anthocyanins.'),
  ('Corn', 'Zea mays', 'Poaceae', 'common', 'A whole grain in disguise — the fiber rides in the kernel skins.'),
  ('Cranberry', 'Vaccinium macrocarpon', 'Ericaceae', 'rare', 'A-type proanthocyanidins — the tart compounds behind its famous reputation.'),
  ('Cucumber', 'Cucumis sativus', 'Cucurbitaceae', 'common', 'Mostly water, but the skin carries the fiber and the polyphenols — don''t peel it.'),
  ('Cumin', 'Cuminum cyminum', 'Apiaceae', 'uncommon', 'The backbone of half the world''s spice blends — seeds with real polyphenol content.'),
  ('Date', 'Phoenix dactylifera', 'Arecaceae', 'uncommon', 'Nature''s caramel wrapped around real fiber — sweetness your microbes share.'),
  ('Eggplant', 'Solanum melongena', 'Solanaceae', 'uncommon', 'Nasunin lives in that deep-purple skin — keep it on.'),
  ('Fennel', 'Foeniculum vulgare', 'Apiaceae', 'rare', 'Anise-sweet bulb, feathery fronds — an Apiaceae rare that roasts into silk.'),
  ('Fig', 'Ficus carica', 'Moraceae', 'rare', 'Ancient, jammy, and fiber-dense — fresh or dried, the seeds do the work.'),
  ('Flaxseed', 'Linum usitatissimum', 'Linaceae', 'uncommon', 'Lignans plus mucilage — grind them fresh or they pass through incognito.'),
  ('Garlic', 'Allium sativum', 'Amaryllidaceae', 'common', 'Tiny clove, huge inulin payload — one of the best-fed guilds'' favorite fuels, plus allicin when crushed.'),
  ('Ginger', 'Zingiber officinale', 'Zingiberaceae', 'uncommon', 'Gingerol brings the heat; a thumb of it in a stir-fry counts as a plant all its own.'),
  ('Grape', 'Vitis vinifera', 'Vitaceae', 'common', 'Resveratrol headlines, but the skins and seeds carry a whole polyphenol cast.'),
  ('Green banana', 'Musa acuminata (unripe)', 'Musaceae', 'uncommon', 'Unripe means resistant starch — a distinct food from its yellow future self.'),
  ('Green pea', 'Pisum sativum', 'Fabaceae', 'common', 'Little green protein-fiber spheres — the easiest legume to say yes to.'),
  ('Hazelnut', 'Corylus avellana', 'Betulaceae', 'rare', 'Proanthocyanidin-rich, especially with skins on — beyond the chocolate-spread cameo.'),
  ('Jerusalem artichoke', 'Helianthus tuberosus', 'Asteraceae', 'legendary', 'The single richest common source of inulin — a legendary feed for the deep-fiber guilds. Start small.'),
  ('Kale', 'Brassica oleracea var. sabellica', 'Brassicaceae', 'uncommon', 'Lutein and glucosinolates in a leaf sturdy enough to massage. The darker the leaf, the more it carries.'),
  ('Kidney bean', 'Phaseolus vulgaris var. nanus', 'Fabaceae', 'uncommon', 'Chili''s backbone — resistant starch and GOS that survive a long simmer.'),
  ('Kimchi', 'Brassica rapa (fermented)', 'Brassicaceae', 'rare', 'Cabbage transformed — live cultures plus the fiber it started with. A probiotic and a plant in one.'),
  ('Kiwi', 'Actinidia deliciosa', 'Actinidiaceae', 'uncommon', 'Actinidin, vitamin C, and a fiber combo studied for keeping things moving.'),
  ('Kombu', 'Saccharina japonica', 'Laminariaceae', 'legendary', 'The umami kelp of dashi — glutamates plus ocean fibers, a legendary find.'),
  ('Kombucha', 'Camellia sinensis (fermented)', 'Theaceae', 'rare', 'Tea plus a culture — tangy, lightly fizzy, and a gentle way to add a fermented find to any day.'),
  ('Leek', 'Allium ampeloprasum', 'Amaryllidaceae', 'uncommon', 'A gentler, sweeter allium — the white base carries the fructans your microbes queue up for.'),
  ('Lemon', 'Citrus x limon', 'Rutaceae', 'common', 'Zest before you juice — the peel oils carry limonene the juice never sees.'),
  ('Lentil', 'Lens culinaris', 'Fabaceae', 'uncommon', 'The fastest-cooking legume, dense in GOS and folate — a guild feast in 25 minutes.'),
  ('Mango', 'Mangifera indica', 'Anacardiaceae', 'uncommon', 'Mangiferin plus carotenoids — sunshine that counts toward your orange.'),
  ('Millet', 'Panicum miliaceum', 'Poaceae', 'rare', 'An ancient, gentle grain — a rare find that cooks like couscous.'),
  ('Mint', 'Mentha spicata', 'Lamiaceae', 'common', 'Menthol freshness that turns water, yogurt, and salads into another plant point.'),
  ('Miso', 'Glycine max (fermented)', 'Fabaceae', 'rare', 'Soybeans aged into savory depth — stir into warm (not boiling) broth to keep the cultures with you.'),
  ('Natto', 'Glycine max (fermented, Bacillus subtilis)', 'Fabaceae', 'legendary', 'The boldest ferment in the guide — sticky, pungent, and famous for vitamin K2. A legendary badge of honor.'),
  ('Nori', 'Pyropia yezoensis', 'Bangiaceae', 'rare', 'The sushi wrap is a sea vegetable — minerals and fibers land plants can''t offer.'),
  ('Nutmeg', 'Myristica fragrans', 'Myristicaceae', 'rare', 'A grating is plenty — warm spice with its own phytochemical signature.'),
  ('Oats', 'Avena sativa', 'Poaceae', 'common', 'Beta-glucan''s home field — the breakfast that feeds your propionate-makers.'),
  ('Okra', 'Abelmoschus esculentus', 'Malvaceae', 'rare', 'That silkiness is mucilage — a soothing gel fiber your butyrate-makers ferment happily.'),
  ('Onion', 'Allium cepa', 'Amaryllidaceae', 'common', 'The everyday prebiotic: fructans plus quercetin in the papery layers. The workhorse of gut gardens.'),
  ('Orange', 'Citrus x sinensis', 'Rutaceae', 'common', 'Eat it, don''t juice it — hesperidin and pectin live in the segments and pith.'),
  ('Oregano', 'Origanum vulgare', 'Lamiaceae', 'uncommon', 'One of the highest polyphenol densities of any herb, dried or fresh.'),
  ('Oyster mushroom', 'Pleurotus ostreatus', 'Pleurotaceae', 'rare', 'Velvety, quick-cooking, and one of the richer beta-glucan mushrooms.'),
  ('Parsley', 'Petroselinum crispum', 'Apiaceae', 'common', 'Not a garnish — one of the densest apigenin sources you can buy.'),
  ('Parsnip', 'Pastinaca sativa', 'Apiaceae', 'rare', 'Carrot''s pale, sweeter cousin — more fiber per bite and criminally underused.'),
  ('Peanut', 'Arachis hypogaea', 'Fabaceae', 'common', 'Botanically a legume, culturally a nut — resveratrol in the skins.'),
  ('Pear', 'Pyrus communis', 'Rosaceae', 'common', 'Gritty texture is stone cells plus pectin — gentle fiber in dessert clothing.'),
  ('Pecan', 'Carya illinoinensis', 'Juglandaceae', 'rare', 'Among the highest polyphenol loads of any nut — pie undersells it.'),
  ('Pineapple', 'Ananas comosus', 'Bromeliaceae', 'uncommon', 'Bromelain lives in the core — the part most people throw away.'),
  ('Pistachio', 'Pistacia vera', 'Anacardiaceae', 'uncommon', 'Green from lutein — one of the few nuts with meaningful carotenoids.'),
  ('Pomegranate', 'Punica granatum', 'Lythraceae', 'rare', 'Ellagitannins your microbes convert to urolithin A — the mitochondria crews'' favorite fruit.'),
  ('Potato', 'Solanum tuberosum', 'Solanaceae', 'common', 'The humble spud turns prebiotic when cooked then COOLED — potato salad is resistant-starch food.'),
  ('Pumpkin', 'Cucurbita pepo', 'Cucurbitaceae', 'uncommon', 'Carotenoid-dense flesh and seeds worth roasting — two finds in one gourd.'),
  ('Pumpkin seed', 'Cucurbita pepo var. styriaca', 'Cucurbitaceae', 'uncommon', 'Zinc, magnesium, and a satisfying crunch — roast the ones from your own pumpkin.'),
  ('Purple sweet potato', 'Ipomoea batatas (purple cultivars)', 'Convolvulaceae', 'rare', 'The orange classic gone violet — anthocyanins in a tuber. Okinawan tables swear by it; cool it after cooking for resistant starch too.'),
  ('Quinoa', 'Chenopodium quinoa', 'Amaranthaceae', 'uncommon', 'A seed posing as a grain — complete protein plus saponins in the rinse water.'),
  ('Radish', 'Raphanus sativus', 'Brassicaceae', 'common', 'A crunchy, peppery crucifer you can eat in seconds — the easy way to sneak a fourth plant into lunch.'),
  ('Raspberry', 'Rubus idaeus', 'Rosaceae', 'uncommon', 'Eight grams of fiber a cup — the highest-fiber berry on the shelf.'),
  ('Romaine lettuce', 'Lactuca sativa', 'Asteraceae', 'common', 'More than crunch: water, folate, and a gentle fiber that makes salads a habit.'),
  ('Rosemary', 'Salvia rosmarinus', 'Lamiaceae', 'uncommon', 'Carnosic acid in needle form — a woody herb that survives every roast.'),
  ('Rye', 'Secale cereale', 'Poaceae', 'rare', 'Dense, dark, and prebiotic — real rye bread feeds crews that white loaves never reach.'),
  ('Sauerkraut', 'Brassica oleracea (fermented)', 'Brassicaceae', 'uncommon', 'The simplest ferment there is: cabbage, salt, time. Choose the refrigerated kind — that''s where the cultures live.'),
  ('Sesame seed', 'Sesamum indicum', 'Pedaliaceae', 'uncommon', 'Sesamin lignans in every sprinkle — tahini is its grown-up form.'),
  ('Shallot', 'Allium cepa var. aggregatum', 'Amaryllidaceae', 'uncommon', 'Onion''s refined cousin, denser in polyphenols per bite than most of the allium family.'),
  ('Shiitake mushroom', 'Lentinula edodes', 'Omphalotaceae', 'uncommon', 'Lentinan — a beta-glucan studied for decades — plus real umami depth.'),
  ('Sorghum', 'Sorghum bicolor', 'Poaceae', 'rare', 'The heirloom cereal with tannins and a pop — it even puffs like popcorn.'),
  ('Soybean', 'Glycine max', 'Fabaceae', 'uncommon', 'The isoflavone legume — edamame is its freshest, simplest form.'),
  ('Spinach', 'Spinacia oleracea', 'Amaranthaceae', 'common', 'Lutein, folate, and chlorophyll that wilts into anything. The gateway green.'),
  ('Spring onion', 'Allium fistulosum', 'Amaryllidaceae', 'common', 'Two plants in one: prebiotic white bulb, chlorophyll-rich green tops. Use the whole thing.'),
  ('Strawberry', 'Fragaria x ananassa', 'Rosaceae', 'common', 'Ellagic acid with universal appeal — the easiest red of the week.'),
  ('Sumac', 'Rhus coriaria', 'Anacardiaceae', 'legendary', 'The lemony crimson dust of Middle Eastern kitchens — a legendary polyphenol find.'),
  ('Sunflower seed', 'Helianthus annuus', 'Asteraceae', 'uncommon', 'Vitamin E and chlorogenic acid by the handful — the lunchbox classic holds up.'),
  ('Sweet potato', 'Ipomoea batatas', 'Convolvulaceae', 'uncommon', 'Orange flesh, carotenoids, and a fiber mix that lands gently. Cool it after cooking for resistant starch.'),
  ('Swiss chard', 'Beta vulgaris subsp. vulgaris', 'Amaranthaceae', 'rare', 'Rainbow stems, beet''s leafy cousin — betalains and magnesium in one dramatic leaf.'),
  ('Tempeh', 'Glycine max (fermented)', 'Fabaceae', 'rare', 'Whole soybeans bound by fungal fermentation — the fiber survives, unlike in most soy foods.'),
  ('Thyme', 'Thymus vulgaris', 'Lamiaceae', 'uncommon', 'Thymol in tiny leaves — a pinch across the week quietly adds up.'),
  ('Tomato', 'Solanum lycopersicum', 'Solanaceae', 'common', 'Lycopene central — and cooking concentrates it. Sauce counts.'),
  ('Turmeric', 'Curcuma longa', 'Zingiberaceae', 'rare', 'Curcumin''s home. Pair with black pepper — its piperine helps curcumin along.'),
  ('Turnip', 'Brassica rapa subsp. rapa', 'Brassicaceae', 'uncommon', 'Old-world staple, two foods in one: peppery root plus greens that outdo it nutritionally.'),
  ('Wakame', 'Undaria pinnatifida', 'Alariaceae', 'rare', 'The silky seaweed in miso soup — fucoidan, a fiber unique to the ocean.'),
  ('Walnut', 'Juglans regia', 'Juglandaceae', 'uncommon', 'Ellagitannins that your microbes turn into urolithins — the brainy-looking nut earns it.'),
  ('Watercress', 'Nasturtium officinale', 'Brassicaceae', 'rare', 'Gram for gram one of the most nutrient-dense leaves known — a rare find worth hunting.'),
  ('White bean', 'Phaseolus vulgaris var. albus', 'Fabaceae', 'uncommon', 'Creamy, mild, and one of the highest-fiber foods per cup in the whole guide.'),
  ('White mushroom', 'Agaricus bisporus', 'Agaricaceae', 'common', 'Fungi, not botanically a plant — but beta-glucans earn it a guide page and your 30.'),
  ('Whole wheat', 'Triticum aestivum', 'Poaceae', 'common', 'Arabinoxylan — wheat bran''s signature fiber — is one of the most overlooked guild feeds.'),
  ('Zucchini', 'Cucurbita pepo var. cylindrica', 'Cucurbitaceae', 'common', 'Mild, fast, and shreds invisibly into sauces — an easy diversity point.')
on conflict (name) do update set
  scientific_name = excluded.scientific_name,
  plant_family = excluded.plant_family,
  rarity_tier = excluded.rarity_tier,
  description = excluded.description;

-- ---- foods — ON CONFLICT (canonical_name); plant_id via plants join --
insert into foods (canonical_name, aliases, is_plant, plant_id, is_fermented, common_hidden_in, categories, protein_tier, energy_tier)
select v.canonical_name, v.aliases, v.is_plant, p.id, v.is_fermented, v.common_hidden_in, v.categories, v.protein_tier, v.energy_tier
from (values
  ('Aged cheese', array['cheddar','parmesan','hard cheese'], false, null, true, array['pasta','pizza','sauce','gratin'], array['dairy','fermented','high_histamine'], 'high', 'high'),
  ('Almond', array['almonds','almond butter','almond meal'], true, 'Almond', false, array['baked_goods','pesto','milk'], array['nut','tree_nut'], 'moderate', 'high'),
  ('Anchovy', array['anchovies','anchovy paste'], false, null, false, array['pizza','dressing','pasta_sauce'], array['fish'], 'high', 'moderate'),
  ('Apple', array['apples','green apple','red apple'], true, 'Apple', false, array['sauce','pie','juice','slaw'], array['fruit','fodmap'], 'low', 'low'),
  ('Apple cider vinegar', array['acv','cider vinegar'], true, null, false, array['dressing','marinade'], array['condiment'], 'none', 'none'),
  ('Artichoke', array['globe artichoke','artichoke heart'], true, 'Artichoke', false, array['dip','pizza_topping'], array['fodmap','green','prebiotic'], 'low', 'low'),
  ('Arugula', array['rocket','rucola'], true, 'Arugula', false, array['salad'], array['cruciferous','leafy_green','green'], 'low', 'low'),
  ('Asparagus', array['asparagus spears'], true, 'Asparagus', false, array['risotto','quiche'], array['fodmap','green','prebiotic'], 'low', 'low'),
  ('Avocado', array['avocados','guacamole'], true, 'Avocado', false, array['guacamole','salad','toast'], array['fruit','green','fodmap'], 'low', 'high'),
  ('Avocado oil', '{}'::text[], true, null, false, array['dressing','marinade'], array['oil'], 'none', 'high'),
  ('Bacon', array['smoked bacon','pancetta'], false, null, false, array['salad','pasta_sauce','soup'], array['meat','red_meat','processed_meat'], 'high', 'high'),
  ('Balsamic vinegar', array['balsamic'], true, null, false, array['dressing','salad'], array['condiment'], 'none', 'none'),
  ('Banana', array['ripe banana','bananas'], true, 'Banana', false, array['smoothie','baked_goods'], array['fruit'], 'low', 'moderate'),
  ('Barley', array['pearl barley','pot barley'], true, 'Barley', false, array['soup','risotto','stew'], array['grain','whole_grain','gluten','fodmap'], 'low', 'moderate'),
  ('Basil', array['fresh basil','sweet basil'], true, 'Basil', false, array['pesto','pasta_sauce','salad'], array['herb_spice','green'], 'low', 'low'),
  ('Beef', array['steak','ground beef','beef mince','red meat','meat'], false, null, false, array['stir_fry','pasta_sauce','curry','soup'], array['meat','red_meat'], 'high', 'moderate'),
  ('Beer', array['lager','ale','pilsner'], true, null, false, '{}'::text[], array['alcohol','gluten'], 'none', 'moderate'),
  ('Beet', array['beetroot','beets'], true, 'Beet', false, array['salad','juice','dip'], array['root_vegetable','red'], 'low', 'low'),
  ('Bell pepper', array['capsicum','sweet pepper','red pepper'], true, 'Bell pepper', false, array['stir_fry','fajita','salsa'], array['nightshade','red'], 'low', 'low'),
  ('Black bean', array['black beans','turtle bean'], true, 'Black bean', false, array['burrito','chili','soup'], array['legume','fodmap'], 'high', 'moderate'),
  ('Black pepper', array['peppercorn','ground pepper'], true, 'Black pepper', false, array['almost_any_savory_dish'], array['herb_spice','white_brown'], 'low', 'low'),
  ('Black tea', array['tea','english breakfast tea','earl grey'], true, null, false, '{}'::text[], array['beverage','caffeine'], 'none', 'none'),
  ('Blackberry', array['blackberries'], true, 'Blackberry', false, array['smoothie','dessert','jam'], array['fruit','berry','blue_purple','polyphenol_rich'], 'low', 'low'),
  ('Blueberry', array['blueberries','wild blueberry'], true, 'Blueberry', false, array['smoothie','muffin','pancake'], array['fruit','berry','blue_purple','polyphenol_rich'], 'low', 'low'),
  ('Bok choy', array['pak choi','chinese cabbage'], true, 'Bok choy', false, array['stir_fry'], array['cruciferous','leafy_green','green'], 'low', 'low'),
  ('Brazil nut', array['brazil nuts'], true, 'Brazil nut', false, array['baked_goods','snack_mix'], array['nut','tree_nut'], 'moderate', 'high'),
  ('Broccoli', array['broccoli florets','tenderstem'], true, 'Broccoli', false, '{}'::text[], array['cruciferous','green','fodmap'], 'low', 'low'),
  ('Brown rice', array['wholegrain rice','brown rice'], true, 'Brown rice', false, array['stir_fry','bowl','pilaf'], array['grain','whole_grain','gluten_free'], 'low', 'moderate'),
  ('Brussels sprouts', array['brussel sprouts'], true, 'Brussels sprouts', false, '{}'::text[], array['cruciferous','fodmap'], 'low', 'low'),
  ('Buckwheat', array['soba','kasha'], true, 'Buckwheat', false, array['noodles','pancake','porridge'], array['grain','whole_grain','gluten_free'], 'low', 'moderate'),
  ('Butter', array['salted butter','unsalted butter'], false, null, false, array['baked_goods','sauce','pastry','toast'], array['dairy'], 'none', 'high'),
  ('Butternut squash', array['butternut','butternut pumpkin'], true, 'Butternut squash', false, array['soup','roast','risotto'], array['squash','orange','fodmap'], 'low', 'low'),
  ('Cabbage', array['green cabbage','red cabbage'], true, 'Cabbage', false, array['slaw','soup'], array['cruciferous'], 'low', 'low'),
  ('Canola oil', array['rapeseed oil','vegetable oil'], true, null, false, array['baked_goods','fried_food'], array['oil'], 'none', 'high'),
  ('Carrot', array['carrots','shredded carrot','baby carrot'], true, 'Carrot', false, array['soup','stir_fry','slaw','stock','cake'], array['root_vegetable','orange'], 'low', 'low'),
  ('Cashew', array['cashews','cashew butter'], true, 'Cashew', false, array['curry','sauce','stir_fry'], array['nut','tree_nut','fodmap'], 'moderate', 'high'),
  ('Cauliflower', array['cauliflower florets'], true, 'Cauliflower', false, array['cauliflower_rice','curry'], array['cruciferous','fodmap'], 'low', 'low'),
  ('Celery', array['celery stalk','celeriac'], true, 'Celery', false, array['soup','stock','salad','stir_fry'], array['herb_spice','green'], 'low', 'low'),
  ('Chia seed', array['chia','chia seeds'], true, 'Chia seed', false, array['pudding','smoothie','baked_goods'], array['seed'], 'moderate', 'high'),
  ('Chicken', array['chicken breast','chicken thigh','grilled chicken','roast chicken','poultry'], false, null, false, array['soup','curry','stir_fry','salad'], array['meat','poultry'], 'high', 'moderate'),
  ('Chickpea', array['garbanzo','hummus bean'], true, 'Chickpea', false, array['hummus','curry','falafel','soup'], array['legume','fodmap'], 'high', 'moderate'),
  ('Chicory root', array['chicory','inulin','witloof root'], true, 'Chicory root', false, array['coffee_substitute','fiber_additive'], array['root_vegetable','fodmap','prebiotic'], 'low', 'low'),
  ('Chili pepper', array['chilli','hot pepper','jalapeno'], true, 'Chili pepper', false, array['curry','salsa','sauce','marinade'], array['nightshade','red','herb_spice'], 'low', 'low'),
  ('Chives', array['chive'], true, 'Chives', false, array['garnish','dip','baked_potato'], array['allium','herb_spice'], 'low', 'low'),
  ('Cilantro', array['coriander leaf','fresh coriander'], true, 'Cilantro', false, array['salsa','curry','garnish'], array['herb_spice','green'], 'low', 'low'),
  ('Cinnamon', array['ground cinnamon','cinnamon stick'], true, 'Cinnamon', false, array['baked_goods','curry','oatmeal','chai'], array['herb_spice','white_brown'], 'low', 'low'),
  ('Clam', array['clams'], false, null, false, array['soup','pasta_sauce'], array['shellfish'], 'high', 'moderate'),
  ('Coconut oil', '{}'::text[], true, null, false, array['curry','baked_goods','smoothie'], array['oil'], 'none', 'high'),
  ('Cod', array['codfish','white fish'], false, null, false, array['fish_and_chips','soup'], array['fish'], 'high', 'moderate'),
  ('Coffee', array['espresso','black coffee','latte','cold brew'], true, null, false, '{}'::text[], array['beverage','caffeine'], 'none', 'none'),
  ('Collard greens', array['collards','spring greens'], true, 'Collard greens', false, array['braise'], array['cruciferous','leafy_green','green'], 'low', 'low'),
  ('Concord grape', array['concord grapes','purple grape'], true, 'Concord grape', false, array['juice','jam'], array['fruit','blue_purple','polyphenol_rich'], 'low', 'low'),
  ('Corn', array['sweetcorn','maize','corn kernels'], true, 'Corn', false, array['salad','soup','salsa'], array['grain','yellow'], 'low', 'moderate'),
  ('Cottage cheese', array['curd cheese'], false, null, false, array['salad'], array['dairy','lactose'], 'high', 'moderate'),
  ('Crab', array['crab meat','crab stick'], false, null, false, array['sushi','salad','soup'], array['shellfish'], 'high', 'moderate'),
  ('Cranberry', array['cranberries','dried cranberry'], true, 'Cranberry', false, array['sauce','juice','baked_goods'], array['fruit','red','polyphenol_rich'], 'low', 'low'),
  ('Cream', array['heavy cream','double cream','whipping cream'], false, null, false, array['soup','pasta_sauce','dessert'], array['dairy','lactose'], 'low', 'high'),
  ('Cream cheese', '{}'::text[], false, null, false, array['bagel','dessert','sushi'], array['dairy','lactose'], 'low', 'high'),
  ('Cucumber', array['cucumbers','gherkin'], true, 'Cucumber', false, array['salad','tzatziki'], array['squash','green'], 'low', 'low'),
  ('Cumin', array['ground cumin','cumin seed','jeera'], true, 'Cumin', false, array['curry','chili','spice_blend'], array['herb_spice','white_brown'], 'low', 'low'),
  ('Date', array['dates','medjool'], true, 'Date', false, array['energy_ball','dessert','smoothie'], array['fruit','fodmap'], 'none', 'moderate'),
  ('Duck', array['duck breast','roast duck'], false, null, false, array['curry'], array['meat','poultry'], 'high', 'high'),
  ('Egg', array['eggs','fried egg','boiled egg','scrambled egg','omelette'], false, null, false, array['baked_goods','dressing','fried_rice','pasta'], array['egg'], 'high', 'moderate'),
  ('Eggplant', array['aubergine','brinjal'], true, 'Eggplant', false, array['curry','dip','ratatouille','moussaka'], array['nightshade','blue_purple'], 'low', 'low'),
  ('Fennel', array['fennel bulb','anise bulb'], true, 'Fennel', false, array['salad','roast'], array['herb_spice','white_brown'], 'low', 'low'),
  ('Fig', array['figs','dried fig'], true, 'Fig', false, array['salad','dessert','jam'], array['fruit','fodmap'], 'low', 'low'),
  ('Fish sauce', array['nam pla','nuoc mam'], false, null, false, array['curry','stir_fry','dressing','marinade'], array['fish','condiment'], 'low', 'none'),
  ('Flaxseed', array['flax','linseed','ground flaxseed'], true, 'Flaxseed', false, array['smoothie','baked_goods','porridge'], array['seed'], 'moderate', 'high'),
  ('Garlic', array['garlic clove','minced garlic','ajo','garlic powder'], true, 'Garlic', false, array['curry','stir_fry','pasta_sauce','dressing','soup','marinade'], array['allium','fodmap','prebiotic'], 'low', 'low'),
  ('Ghee', array['clarified butter'], false, null, false, array['curry'], array['dairy'], 'none', 'high'),
  ('Ginger', array['fresh ginger','ginger root'], true, 'Ginger', false, array['curry','stir_fry','marinade','smoothie','tea'], array['root_vegetable','herb_spice'], 'low', 'low'),
  ('Grape', array['grapes','green grape','red grape'], true, 'Grape', false, array['salad','juice','snack'], array['fruit'], 'low', 'low'),
  ('Green banana', array['unripe banana','cooking banana','plantain'], true, 'Green banana', false, array['smoothie','curry'], array['fruit'], 'low', 'low'),
  ('Green pea', array['peas','garden pea','petit pois'], true, 'Green pea', false, array['soup','curry','fried_rice'], array['legume','green','fodmap'], 'high', 'moderate'),
  ('Green tea', array['matcha','sencha','green tea leaves'], true, null, false, array['latte','smoothie'], array['beverage','polyphenol_rich'], 'none', 'none'),
  ('Ham', array['sliced ham','prosciutto'], false, null, false, array['sandwich','salad','pizza'], array['meat','red_meat','processed_meat'], 'high', 'high'),
  ('Hazelnut', array['hazelnuts','filbert'], true, 'Hazelnut', false, array['dessert','spread','baked_goods'], array['nut','tree_nut'], 'moderate', 'high'),
  ('Honey', array['raw honey'], false, null, false, array['baked_goods','dressing','tea'], array['sweetener','fodmap'], 'none', 'moderate'),
  ('Hot sauce', array['sriracha','chili sauce','tabasco'], true, null, false, array['stir_fry','marinade','tacos'], array['condiment'], 'none', 'low'),
  ('Ice cream', array['gelato','soft serve'], false, null, false, array['dessert'], array['dairy','lactose'], 'low', 'high'),
  ('Jerusalem artichoke', array['sunchoke','sunroot'], true, 'Jerusalem artichoke', false, array['soup','roast'], array['root_vegetable','fodmap','prebiotic'], 'low', 'low'),
  ('Kale', array['curly kale','lacinato','cavolo nero'], true, 'Kale', false, array['smoothie','chips'], array['cruciferous','leafy_green','green'], 'low', 'low'),
  ('Kefir', array['milk kefir','kefir drink'], false, null, true, array['smoothie'], array['dairy','fermented','high_histamine'], 'moderate', 'moderate'),
  ('Ketchup', array['tomato ketchup','catsup'], true, null, false, array['sandwich','fried_food'], array['condiment'], 'none', 'low'),
  ('Kidney bean', array['kidney beans','rajma'], true, 'Kidney bean', false, array['chili','curry','salad'], array['legume','fodmap'], 'high', 'moderate'),
  ('Kimchi', array['fermented kimchi','baechu'], true, 'Kimchi', true, array['stir_fry','rice_bowl','stew'], array['fermented','cruciferous','allium','high_histamine','fodmap'], 'low', 'low'),
  ('Kiwi', array['kiwifruit','kiwis'], true, 'Kiwi', false, array['smoothie','salad','dessert'], array['fruit','green'], 'low', 'low'),
  ('Kombu', array['kelp','dashi kelp'], true, 'Kombu', false, array['dashi','broth','bean_cooking'], array['seaweed'], 'low', 'low'),
  ('Kombucha', array['fermented tea','booch'], true, 'Kombucha', true, '{}'::text[], array['fermented','beverage','polyphenol_rich'], 'none', 'low'),
  ('Lamb', array['lamb chop','ground lamb'], false, null, false, array['curry','stew'], array['meat','red_meat'], 'high', 'high'),
  ('Leek', array['leeks'], true, 'Leek', false, array['soup','quiche','stock','gratin'], array['allium','fodmap','prebiotic'], 'low', 'low'),
  ('Lemon', array['lemons','lemon juice'], true, 'Lemon', false, array['dressing','marinade','dessert','juice'], array['fruit','citrus','yellow'], 'low', 'low'),
  ('Lentil', array['lentils','dal','red lentil'], true, 'Lentil', false, array['dal','soup','curry','stew'], array['legume','fodmap'], 'high', 'moderate'),
  ('Lobster', array['lobster tail'], false, null, false, '{}'::text[], array['shellfish'], 'high', 'moderate'),
  ('Mackerel', array['smoked mackerel'], false, null, false, array['salad'], array['fish'], 'high', 'moderate'),
  ('Mango', array['mangoes','mango'], true, 'Mango', false, array['smoothie','salsa','curry'], array['fruit','orange','fodmap'], 'low', 'low'),
  ('Maple syrup', '{}'::text[], true, null, false, array['baked_goods','pancakes'], array['sweetener'], 'none', 'moderate'),
  ('Mayonnaise', array['mayo','aioli'], false, null, false, array['sandwich','salad','dressing'], array['egg','condiment'], 'low', 'high'),
  ('Milk', array['whole milk','skim milk','cows milk'], false, null, false, array['smoothie','baked_goods','sauce','porridge'], array['dairy','lactose'], 'moderate', 'moderate'),
  ('Millet', array['millet grain'], true, 'Millet', false, array['porridge','flatbread'], array['grain','whole_grain','gluten_free'], 'low', 'moderate'),
  ('Mint', array['fresh mint','spearmint'], true, 'Mint', false, array['salad','tea','dessert','chutney'], array['herb_spice','green'], 'low', 'low'),
  ('Miso', array['miso paste','red miso','white miso'], true, 'Miso', true, array['soup','marinade','dressing'], array['fermented','soy','high_histamine','fodmap'], 'moderate', 'low'),
  ('Mozzarella', array['fresh mozzarella','buffalo mozzarella'], false, null, false, array['pizza','salad','pasta_sauce'], array['dairy','lactose'], 'high', 'high'),
  ('Mussels', array['mussel'], false, null, false, array['soup','pasta_sauce'], array['shellfish'], 'high', 'moderate'),
  ('Mustard', array['dijon','yellow mustard','wholegrain mustard'], true, null, false, array['dressing','sandwich','marinade'], array['condiment'], 'none', 'low'),
  ('Natto', array['fermented soybeans'], true, 'Natto', true, array['rice_bowl'], array['fermented','soy','high_histamine'], 'high', 'moderate'),
  ('Nori', array['seaweed sheet','laver'], true, 'Nori', false, array['sushi','snack','garnish'], array['seaweed'], 'low', 'low'),
  ('Nutmeg', array['ground nutmeg'], true, 'Nutmeg', false, array['baked_goods','bechamel','curry'], array['herb_spice','white_brown'], 'low', 'low'),
  ('Oats', array['oatmeal','rolled oats','porridge','oat'], true, 'Oats', false, array['granola','smoothie','baked_goods'], array['grain','whole_grain'], 'low', 'moderate'),
  ('Okra', array['okra','ladies fingers','bhindi'], true, 'Okra', false, array['gumbo','curry','stew'], array['green','fodmap'], 'low', 'low'),
  ('Olive oil', array['extra virgin olive oil','evoo'], true, null, false, array['dressing','marinade','pasta_sauce','pesto'], array['oil'], 'none', 'high'),
  ('Onion', array['yellow onion','red onion','white onion','diced onion'], true, 'Onion', false, array['curry','soup','stock','sauce','dressing','stir_fry','casserole'], array['allium','fodmap','prebiotic'], 'low', 'low'),
  ('Orange', array['oranges','mandarin','clementine'], true, 'Orange', false, array['juice','salad','dessert'], array['fruit','citrus','orange'], 'low', 'low'),
  ('Oregano', array['fresh oregano','dried oregano'], true, 'Oregano', false, array['pizza_sauce','pasta_sauce','marinade'], array['herb_spice','green'], 'low', 'low'),
  ('Oyster', array['oysters'], false, null, false, '{}'::text[], array['shellfish'], 'high', 'moderate'),
  ('Oyster mushroom', array['oyster mushrooms'], true, 'Oyster mushroom', false, array['stir_fry','soup'], array['mushroom','white_brown'], 'low', 'low'),
  ('Parmesan', array['parmigiano','grana padano','parmesan cheese'], false, null, true, array['pasta_sauce','pesto','pizza','salad'], array['dairy','fermented','high_histamine'], 'high', 'high'),
  ('Parsley', array['flat-leaf parsley','curly parsley'], true, 'Parsley', false, array['garnish','tabbouleh','sauce'], array['herb_spice','green'], 'low', 'low'),
  ('Parsnip', array['parsnips'], true, 'Parsnip', false, array['soup','roast','mash'], array['root_vegetable','white_brown'], 'low', 'low'),
  ('Peanut', array['peanuts','groundnut','peanut butter'], true, 'Peanut', false, array['satay','sauce','dressing','baked_goods'], array['legume','peanut'], 'high', 'moderate'),
  ('Peanut oil', array['groundnut oil'], true, null, false, array['stir_fry','fried_food'], array['oil','peanut'], 'none', 'high'),
  ('Pear', array['pears','bartlett','bosc'], true, 'Pear', false, array['salad','dessert','juice'], array['fruit','fodmap'], 'low', 'low'),
  ('Pecan', array['pecans'], true, 'Pecan', false, array['pie','salad','baked_goods'], array['nut','tree_nut'], 'moderate', 'high'),
  ('Pineapple', array['pineapples','ananas'], true, 'Pineapple', false, array['smoothie','salsa','dessert'], array['fruit','yellow'], 'low', 'low'),
  ('Pistachio', array['pistachios'], true, 'Pistachio', false, array['dessert','baked_goods'], array['nut','tree_nut','fodmap'], 'moderate', 'high'),
  ('Pomegranate', array['pomegranate seeds','arils'], true, 'Pomegranate', false, array['salad','juice','garnish'], array['fruit','red','polyphenol_rich'], 'low', 'low'),
  ('Pork', array['pork chop','pork loin','pork belly'], false, null, false, array['stir_fry','soup'], array['meat','red_meat'], 'high', 'high'),
  ('Potato', array['potatoes','white potato','russet'], true, 'Potato', false, array['mash','fries','soup','gratin'], array['root_vegetable'], 'low', 'moderate'),
  ('Pumpkin', array['pumpkin puree','winter squash'], true, 'Pumpkin', false, array['soup','pie','curry'], array['squash','orange'], 'low', 'low'),
  ('Pumpkin seed', array['pepitas','pumpkin seeds'], true, 'Pumpkin seed', false, array['salad','snack_mix','granola'], array['seed'], 'moderate', 'high'),
  ('Purple sweet potato', array['purple sweet potatoes','okinawan sweet potato','stokes purple','murasaki','ube'], true, 'Purple sweet potato', false, array['fries','mash','curry'], array['root_vegetable','purple'], 'low', 'moderate'),
  ('Quinoa', array['quinoa grain'], true, 'Quinoa', false, array['salad','bowl','porridge'], array['grain','whole_grain','gluten_free'], 'low', 'moderate'),
  ('Radish', array['radishes','daikon'], true, 'Radish', false, array['salad','slaw'], array['cruciferous','root_vegetable'], 'low', 'low'),
  ('Raspberry', array['raspberries'], true, 'Raspberry', false, array['smoothie','dessert','jam'], array['fruit','berry','red','polyphenol_rich'], 'low', 'low'),
  ('Rice vinegar', array['rice wine vinegar'], true, null, false, array['sushi','dressing','stir_fry'], array['condiment'], 'none', 'none'),
  ('Romaine lettuce', array['romaine','cos lettuce','lettuce'], true, 'Romaine lettuce', false, array['salad','wrap'], array['leafy_green','green'], 'low', 'low'),
  ('Rosemary', array['fresh rosemary'], true, 'Rosemary', false, array['roast','marinade','bread'], array['herb_spice','green'], 'low', 'low'),
  ('Rye', array['rye bread','pumpernickel'], true, 'Rye', false, array['bread','crackers'], array['grain','whole_grain','gluten','fodmap'], 'low', 'moderate'),
  ('Salami', array['cured salami','pepperoni'], false, null, false, array['sandwich','pizza'], array['meat','red_meat','processed_meat'], 'high', 'high'),
  ('Salmon', array['salmon fillet','grilled salmon'], false, null, false, array['sushi','salad'], array['fish'], 'high', 'moderate'),
  ('Sardines', array['canned sardines'], false, null, false, array['salad','pasta_sauce'], array['fish'], 'high', 'moderate'),
  ('Sauerkraut', array['fermented cabbage','kraut'], true, 'Sauerkraut', true, array['hot_dog_topping','salad'], array['fermented','cruciferous','high_histamine','fodmap'], 'low', 'low'),
  ('Sausage', array['pork sausage','bratwurst','chorizo'], false, null, false, array['soup','pasta_sauce','stew'], array['meat','processed_meat'], 'high', 'high'),
  ('Scallop', array['scallops'], false, null, false, array['pasta_sauce'], array['shellfish'], 'high', 'moderate'),
  ('Sesame oil', array['toasted sesame oil'], true, null, false, array['stir_fry','dressing','marinade'], array['oil','sesame'], 'none', 'high'),
  ('Sesame seed', array['sesame','tahini','til'], true, 'Sesame seed', false, array['tahini','dressing','baked_goods','stir_fry'], array['seed','sesame'], 'moderate', 'high'),
  ('Shallot', array['shallots','eschalot'], true, 'Shallot', false, array['dressing','sauce','stir_fry'], array['allium','fodmap','prebiotic'], 'low', 'low'),
  ('Shiitake mushroom', array['shiitake','dried shiitake'], true, 'Shiitake mushroom', false, array['stir_fry','broth','ramen'], array['mushroom','white_brown','fodmap'], 'low', 'low'),
  ('Shrimp', array['prawns','prawn','king prawn'], false, null, false, array['stir_fry','curry','pasta_sauce'], array['shellfish'], 'high', 'moderate'),
  ('Smoked salmon', array['lox','cured salmon'], false, null, false, array['bagel','salad','sushi'], array['fish'], 'high', 'moderate'),
  ('Sorghum', array['jowar','milo'], true, 'Sorghum', false, array['porridge','flour'], array['grain','whole_grain','gluten_free'], 'low', 'moderate'),
  ('Sourdough bread', array['sourdough','levain'], true, 'Whole wheat', true, array['sandwich','toast'], array['fermented','grain','gluten','wheat'], 'moderate', 'moderate'),
  ('Soy sauce', array['shoyu','light soy sauce','dark soy sauce'], true, null, false, array['stir_fry','marinade','sushi','fried_rice'], array['soy','gluten','wheat','condiment'], 'low', 'none'),
  ('Soybean', array['edamame','soya bean'], true, 'Soybean', false, array['stir_fry','salad'], array['legume','soy','fodmap'], 'high', 'moderate'),
  ('Spinach', array['baby spinach','spinach leaves'], true, 'Spinach', false, array['curry','dip','smoothie','lasagne'], array['leafy_green','green'], 'low', 'low'),
  ('Spring onion', array['scallion','green onion'], true, 'Spring onion', false, array['stir_fry','garnish','noodle_soup'], array['allium','fodmap'], 'low', 'low'),
  ('Squid', array['calamari','cuttlefish'], false, null, false, array['stir_fry'], array['shellfish'], 'high', 'moderate'),
  ('Strawberry', array['strawberries'], true, 'Strawberry', false, array['smoothie','dessert','jam'], array['fruit','berry','red'], 'low', 'low'),
  ('Sugar', array['white sugar','cane sugar','brown sugar'], true, null, false, array['baked_goods','dessert','sauce'], array['sweetener'], 'none', 'moderate'),
  ('Sumac', array['ground sumac'], true, 'Sumac', false, array['dressing','spice_blend','garnish'], array['herb_spice','red'], 'low', 'low'),
  ('Sunflower oil', '{}'::text[], true, null, false, array['fried_food','dressing'], array['oil'], 'none', 'high'),
  ('Sunflower seed', array['sunflower seeds','sunflower butter'], true, 'Sunflower seed', false, array['salad','baked_goods','snack_mix'], array['seed'], 'moderate', 'high'),
  ('Sweet potato', array['sweet potatoes','yam','kumara'], true, 'Sweet potato', false, array['fries','mash','curry'], array['root_vegetable','orange'], 'low', 'moderate'),
  ('Swiss chard', array['chard','silverbeet'], true, 'Swiss chard', false, array['saute'], array['leafy_green','green'], 'low', 'low'),
  ('Tamari', array['gluten free soy sauce'], true, null, false, array['stir_fry','marinade'], array['soy','condiment'], 'low', 'none'),
  ('Tempeh', array['fermented soy cake'], true, 'Tempeh', true, array['stir_fry','sandwich'], array['fermented','soy'], 'high', 'moderate'),
  ('Thyme', array['fresh thyme'], true, 'Thyme', false, array['stock','roast','stew'], array['herb_spice','green'], 'low', 'low'),
  ('Tilapia', '{}'::text[], false, null, false, '{}'::text[], array['fish'], 'high', 'moderate'),
  ('Tofu', array['bean curd','firm tofu','silken tofu'], true, 'Soybean', false, array['stir_fry','curry','soup','scramble'], array['soy','legume'], 'high', 'moderate'),
  ('Tomato', array['tomatoes','cherry tomato','roma'], true, 'Tomato', false, array['sauce','curry','salsa','soup'], array['nightshade','red'], 'low', 'low'),
  ('Trout', array['rainbow trout'], false, null, false, '{}'::text[], array['fish'], 'high', 'moderate'),
  ('Tuna', array['tuna steak','canned tuna','ahi tuna'], false, null, false, array['sushi','salad','sandwich'], array['fish'], 'high', 'moderate'),
  ('Turkey', array['turkey breast','ground turkey'], false, null, false, array['soup','salad','sandwich'], array['meat','poultry'], 'high', 'moderate'),
  ('Turmeric', array['fresh turmeric','turmeric root'], true, 'Turmeric', false, array['curry','golden_milk','rice'], array['root_vegetable','herb_spice','yellow'], 'low', 'low'),
  ('Turnip', array['turnips','swede'], true, 'Turnip', false, array['soup','stew'], array['cruciferous','root_vegetable'], 'low', 'low'),
  ('Vinegar', array['white vinegar','distilled vinegar'], true, null, false, array['dressing','pickles','marinade'], array['condiment'], 'none', 'none'),
  ('Wakame', array['seaweed salad','wakame'], true, 'Wakame', false, array['miso_soup','salad'], array['seaweed'], 'low', 'low'),
  ('Walnut', array['walnuts'], true, 'Walnut', false, array['salad','baked_goods','pesto'], array['nut','tree_nut'], 'moderate', 'high'),
  ('Watercress', array['water cress'], true, 'Watercress', false, array['salad','soup'], array['cruciferous','leafy_green','green'], 'low', 'low'),
  ('White bean', array['cannellini','navy bean','haricot'], true, 'White bean', false, array['soup','stew','dip'], array['legume','fodmap'], 'high', 'moderate'),
  ('White mushroom', array['button mushroom','cremini','portobello'], true, 'White mushroom', false, array['stir_fry','soup','sauce','pizza_topping'], array['mushroom','white_brown','fodmap'], 'low', 'low'),
  ('Whole wheat', array['wholemeal','whole wheat bread','wheat'], true, 'Whole wheat', false, array['bread','pasta','baked_goods','sauce_thickener'], array['grain','whole_grain','gluten','wheat','fodmap'], 'low', 'moderate'),
  ('Wine', array['red wine','white wine','rose'], true, null, false, '{}'::text[], array['alcohol'], 'none', 'moderate'),
  ('Worcestershire sauce', '{}'::text[], false, null, false, array['marinade','stew'], array['fish','condiment'], 'none', 'none'),
  ('Yogurt', array['plain yogurt','greek yogurt','curd'], false, null, true, array['smoothie','dressing','dip','marinade'], array['dairy','fermented'], 'moderate', 'moderate'),
  ('Zucchini', array['courgette','summer squash'], true, 'Zucchini', false, array['fritter','ratatouille','bread'], array['squash','green'], 'low', 'low')
) as v(canonical_name, aliases, is_plant, plant_name, is_fermented, common_hidden_in, categories, protein_tier, energy_tier)
left join plants p on p.name = v.plant_name
on conflict (canonical_name) do update set
  aliases = excluded.aliases,
  is_plant = excluded.is_plant,
  plant_id = excluded.plant_id,
  is_fermented = excluded.is_fermented,
  common_hidden_in = excluded.common_hidden_in,
  categories = excluded.categories,
  protein_tier = excluded.protein_tier,
  energy_tier = excluded.energy_tier;

-- ---- food_fibers — ON CONFLICT (food_id,fiber_id); Fence 4 grams -----
insert into food_fibers (food_id, fiber_id, relative_amount, est_grams_per_serving)
select fo.id, fi.id, v.relative_amount::amount_tier, v.est_grams
from (values
  ('Apple', 'pectin', 'primary', 1.5),
  ('Asparagus', 'fos', 'minor', 0.6),
  ('Asparagus', 'inulin', 'moderate', 1.5),
  ('Banana', 'fos', 'minor', 0.5),
  ('Barley', 'arabinoxylan', 'moderate', 1.5),
  ('Barley', 'beta_glucan', 'primary', 2.5),
  ('Beet', 'pectin', 'minor', 0.7),
  ('Black bean', 'gos', 'primary', 2.2),
  ('Blueberry', 'pectin', 'minor', 0.5),
  ('Brown rice', 'rs3', 'moderate', 1.5),
  ('Carrot', 'pectin', 'moderate', 1.2),
  ('Chia seed', 'mucilage', 'primary', 3.5),
  ('Chickpea', 'gos', 'primary', 2.5),
  ('Chicory root', 'inulin', 'primary', 10.0),
  ('Flaxseed', 'mucilage', 'primary', 3.0),
  ('Garlic', 'fos', 'moderate', 1.0),
  ('Garlic', 'inulin', 'primary', 2.0),
  ('Green banana', 'rs2', 'primary', 4.5),
  ('Green pea', 'gos', 'moderate', 1.2),
  ('Jerusalem artichoke', 'inulin', 'primary', 6.0),
  ('Kidney bean', 'gos', 'primary', 2.0),
  ('Leek', 'fos', 'minor', 0.5),
  ('Leek', 'inulin', 'moderate', 1.5),
  ('Lemon', 'pectin', 'moderate', 1.0),
  ('Lentil', 'gos', 'moderate', 1.8),
  ('Millet', 'arabinoxylan', 'minor', 0.7),
  ('Oats', 'arabinoxylan', 'minor', 0.8),
  ('Oats', 'beta_glucan', 'primary', 3.0),
  ('Oats', 'rs2', 'minor', 0.5),
  ('Okra', 'mucilage', 'primary', 2.0),
  ('Onion', 'fos', 'moderate', 1.0),
  ('Onion', 'inulin', 'moderate', 1.2),
  ('Orange', 'pectin', 'moderate', 1.5),
  ('Oyster mushroom', 'beta_glucan', 'moderate', 1.0),
  ('Peanut', 'gos', 'minor', 0.6),
  ('Pear', 'pectin', 'moderate', 1.4),
  ('Potato', 'rs3', 'moderate', 2.0),
  ('Rye', 'arabinoxylan', 'primary', 3.0),
  ('Shallot', 'inulin', 'moderate', 1.3),
  ('Shiitake mushroom', 'beta_glucan', 'moderate', 1.2),
  ('Sorghum', 'arabinoxylan', 'minor', 0.8),
  ('Soybean', 'gos', 'moderate', 1.5),
  ('Spinach', 'pectin', 'minor', 0.6),
  ('White bean', 'gos', 'moderate', 1.8),
  ('White mushroom', 'beta_glucan', 'moderate', 1.0),
  ('Whole wheat', 'arabinoxylan', 'primary', 2.5),
  ('Whole wheat', 'fos', 'minor', 0.5)
) as v(food, fiber, relative_amount, est_grams)
join foods fo on fo.canonical_name = v.food
join fibers fi on fi.name = v.fiber
on conflict (food_id, fiber_id) do update set
  relative_amount = excluded.relative_amount,
  est_grams_per_serving = excluded.est_grams_per_serving;

-- ---- food_colors — ON CONFLICT (food_id,color_id) do nothing (pk-only)
insert into food_colors (food_id, color_id)
select fo.id, v.color::color_name
from (values
  ('Aged cheese', 'yellow'),
  ('Almond', 'white_brown'),
  ('Apple', 'green'),
  ('Apple', 'red'),
  ('Artichoke', 'green'),
  ('Arugula', 'green'),
  ('Asparagus', 'green'),
  ('Avocado', 'green'),
  ('Banana', 'yellow'),
  ('Barley', 'white_brown'),
  ('Basil', 'green'),
  ('Beet', 'red'),
  ('Bell pepper', 'red'),
  ('Black bean', 'blue_purple'),
  ('Black pepper', 'white_brown'),
  ('Blackberry', 'blue_purple'),
  ('Blueberry', 'blue_purple'),
  ('Bok choy', 'green'),
  ('Brazil nut', 'white_brown'),
  ('Broccoli', 'green'),
  ('Brown rice', 'white_brown'),
  ('Brussels sprouts', 'green'),
  ('Buckwheat', 'white_brown'),
  ('Butternut squash', 'orange'),
  ('Cabbage', 'green'),
  ('Carrot', 'orange'),
  ('Cashew', 'white_brown'),
  ('Cauliflower', 'white_brown'),
  ('Celery', 'green'),
  ('Chia seed', 'white_brown'),
  ('Chickpea', 'white_brown'),
  ('Chicory root', 'white_brown'),
  ('Chili pepper', 'red'),
  ('Chives', 'green'),
  ('Cilantro', 'green'),
  ('Cinnamon', 'white_brown'),
  ('Collard greens', 'green'),
  ('Concord grape', 'blue_purple'),
  ('Corn', 'yellow'),
  ('Cranberry', 'red'),
  ('Cucumber', 'green'),
  ('Cumin', 'white_brown'),
  ('Date', 'white_brown'),
  ('Eggplant', 'blue_purple'),
  ('Fennel', 'white_brown'),
  ('Fig', 'blue_purple'),
  ('Flaxseed', 'white_brown'),
  ('Garlic', 'white_brown'),
  ('Ginger', 'white_brown'),
  ('Grape', 'green'),
  ('Green banana', 'green'),
  ('Green banana', 'white_brown'),
  ('Green pea', 'green'),
  ('Green tea', 'green'),
  ('Hazelnut', 'white_brown'),
  ('Jerusalem artichoke', 'white_brown'),
  ('Kale', 'green'),
  ('Kefir', 'white_brown'),
  ('Kidney bean', 'red'),
  ('Kimchi', 'red'),
  ('Kiwi', 'green'),
  ('Kombucha', 'white_brown'),
  ('Kombu', 'green'),
  ('Leek', 'white_brown'),
  ('Lemon', 'yellow'),
  ('Lentil', 'white_brown'),
  ('Mango', 'orange'),
  ('Millet', 'yellow'),
  ('Mint', 'green'),
  ('Miso', 'white_brown'),
  ('Natto', 'white_brown'),
  ('Nori', 'green'),
  ('Nutmeg', 'white_brown'),
  ('Oats', 'white_brown'),
  ('Okra', 'green'),
  ('Onion', 'white_brown'),
  ('Orange', 'orange'),
  ('Oregano', 'green'),
  ('Oyster mushroom', 'white_brown'),
  ('Parsley', 'green'),
  ('Parsnip', 'white_brown'),
  ('Peanut', 'white_brown'),
  ('Pear', 'green'),
  ('Pecan', 'white_brown'),
  ('Pineapple', 'yellow'),
  ('Pistachio', 'green'),
  ('Pomegranate', 'red'),
  ('Potato', 'white_brown'),
  ('Pumpkin seed', 'green'),
  ('Pumpkin', 'orange'),
  ('Purple sweet potato', 'blue_purple'),
  ('Quinoa', 'white_brown'),
  ('Radish', 'red'),
  ('Raspberry', 'red'),
  ('Romaine lettuce', 'green'),
  ('Rosemary', 'green'),
  ('Rye', 'white_brown'),
  ('Sauerkraut', 'white_brown'),
  ('Sesame seed', 'white_brown'),
  ('Shallot', 'white_brown'),
  ('Shiitake mushroom', 'white_brown'),
  ('Sorghum', 'white_brown'),
  ('Sourdough bread', 'white_brown'),
  ('Soybean', 'green'),
  ('Spinach', 'green'),
  ('Spring onion', 'green'),
  ('Strawberry', 'red'),
  ('Sumac', 'red'),
  ('Sunflower seed', 'white_brown'),
  ('Sweet potato', 'orange'),
  ('Swiss chard', 'green'),
  ('Tempeh', 'white_brown'),
  ('Thyme', 'green'),
  ('Tofu', 'white_brown'),
  ('Tomato', 'red'),
  ('Turmeric', 'yellow'),
  ('Turnip', 'white_brown'),
  ('Wakame', 'green'),
  ('Walnut', 'white_brown'),
  ('Watercress', 'green'),
  ('White bean', 'white_brown'),
  ('White mushroom', 'white_brown'),
  ('Whole wheat', 'white_brown'),
  ('Yogurt', 'white_brown'),
  ('Zucchini', 'green')
) as v(food, color)
join foods fo on fo.canonical_name = v.food
on conflict (food_id, color_id) do nothing;

-- ---- food_phytochemicals — ON CONFLICT (pk) do nothing (pk-only) -----
insert into food_phytochemicals (food_id, phytochemical_id)
select fo.id, ph.id
from (values
  ('Almond', 'beta_sitosterol'),
  ('Apple', 'chlorogenic_acid'),
  ('Apple', 'quercetin'),
  ('Arugula', 'glucosinolate'),
  ('Asparagus', 'asparagoside'),
  ('Avocado', 'beta_sitosterol'),
  ('Basil', 'chlorophyll'),
  ('Basil', 'linalool'),
  ('Beet', 'betanidin'),
  ('Beet', 'betanin'),
  ('Beet', 'isobetanin'),
  ('Beet', 'vulgaxanthin'),
  ('Bell pepper', 'beta_cryptoxanthin'),
  ('Bell pepper', 'capsaicin'),
  ('Black pepper', 'chavicine'),
  ('Black pepper', 'piperine'),
  ('Blackberry', 'anthocyanin'),
  ('Blackberry', 'ellagic_acid'),
  ('Blueberry', 'anthocyanin'),
  ('Bok choy', 'glucosinolate'),
  ('Broccoli', 'brassicasterol'),
  ('Broccoli', 'glucosinolate'),
  ('Broccoli', 'lutein'),
  ('Broccoli', 'pheophytin'),
  ('Broccoli', 'sulforaphane'),
  ('Brussels sprouts', 'glucosinolate'),
  ('Brussels sprouts', 'sulforaphane'),
  ('Butternut squash', 'beta_carotene'),
  ('Cabbage', 'glucosinolate'),
  ('Carrot', 'alpha_carotene'),
  ('Carrot', 'beta_carotene'),
  ('Cauliflower', 'glucosinolate'),
  ('Chickpea', 'chickpea_saponin'),
  ('Chili pepper', 'capsaicin'),
  ('Chives', 'kaempferol'),
  ('Cinnamon', 'chlorogenic_acid'),
  ('Cinnamon', 'eugenol'),
  ('Collard greens', 'chlorophyll'),
  ('Collard greens', 'lutein'),
  ('Concord grape', 'anthocyanin'),
  ('Concord grape', 'resveratrol'),
  ('Corn', 'zeaxanthin'),
  ('Cranberry', 'anthocyanin'),
  ('Eggplant', 'anthocyanin'),
  ('Eggplant', 'solanine'),
  ('Fig', 'anthocyanin'),
  ('Flaxseed', 'secoisolariciresinol'),
  ('Garlic', 'allicin'),
  ('Garlic', 'diallyl_disulfide'),
  ('Garlic', 's_allyl_cysteine'),
  ('Grape', 'resveratrol'),
  ('Green tea', 'caffeine'),
  ('Green tea', 'catechin'),
  ('Green tea', 'epigallocatechin_gallate'),
  ('Kale', 'chlorophyll_b'),
  ('Kale', 'kaempferol'),
  ('Kale', 'lutein'),
  ('Kale', 'sulforaphane'),
  ('Kombucha', 'catechin'),
  ('Leek', 'kaempferol'),
  ('Lemon', 'hesperidin'),
  ('Mango', 'beta_carotene'),
  ('Mint', 'menthol'),
  ('Miso', 'genistein'),
  ('Oats', 'avenacoside'),
  ('Oats', 'avenasterol'),
  ('Oats', 'beta_sitosterol'),
  ('Onion', 'quercetin'),
  ('Onion', 's_allyl_cysteine'),
  ('Orange', 'beta_cryptoxanthin'),
  ('Orange', 'hesperidin'),
  ('Oregano', 'carnosic_acid'),
  ('Parsley', 'kaempferol'),
  ('Pineapple', 'naringenin'),
  ('Pistachio', 'lutein'),
  ('Pomegranate', 'ellagic_acid'),
  ('Pomegranate', 'punicalagin'),
  ('Potato', 'solanine'),
  ('Pumpkin', 'beta_carotene'),
  ('Purple sweet potato', 'anthocyanin'),
  ('Quinoa', 'quinoa_saponin'),
  ('Radish', 'glucosinolate'),
  ('Raspberry', 'anthocyanin'),
  ('Raspberry', 'ellagic_acid'),
  ('Romaine lettuce', 'lutein'),
  ('Rosemary', 'alpha_pinene'),
  ('Rosemary', 'carnosic_acid'),
  ('Sesame seed', 'secoisolariciresinol'),
  ('Soybean', 'genistein'),
  ('Soybean', 'stigmasterol'),
  ('Spinach', 'chlorophyll'),
  ('Spinach', 'chlorophyll_a'),
  ('Spinach', 'chlorophyllin'),
  ('Spinach', 'lutein'),
  ('Spinach', 'zeaxanthin'),
  ('Strawberry', 'anthocyanin'),
  ('Strawberry', 'ellagic_acid'),
  ('Sumac', 'ellagic_acid'),
  ('Sunflower seed', 'beta_sitosterol'),
  ('Sunflower seed', 'campesterol'),
  ('Sweet potato', 'beta_carotene'),
  ('Swiss chard', 'betanin'),
  ('Swiss chard', 'indicaxanthin'),
  ('Swiss chard', 'lutein'),
  ('Tempeh', 'genistein'),
  ('Tofu', 'genistein'),
  ('Tomato', 'lycopene'),
  ('Turmeric', 'curcumin'),
  ('Walnut', 'ellagic_acid'),
  ('Watercress', 'glucosinolate')
) as v(food, phyto)
join foods fo on fo.canonical_name = v.food
join phytochemicals ph on ph.name = v.phyto
on conflict (food_id, phytochemical_id) do nothing;

-- ---- food_guild_feeds — ON CONFLICT (food_id,guild_id) do update -----
insert into food_guild_feeds (food_id, guild_id, relevance)
select fo.id, g.id, v.relevance::amount_tier
from (values
  ('Almond', 'stone_breakers', 'minor'),
  ('Apple', 'anti_inflammatory_arsenal', 'primary'),
  ('Asparagus', 'base_layer', 'moderate'),
  ('Asparagus', 'vitamin_lab', 'minor'),
  ('Barley', 'appetite_crew', 'primary'),
  ('Beet', 'stone_breakers', 'moderate'),
  ('Beet', 'vitamin_lab', 'minor'),
  ('Black bean', 'base_layer', 'moderate'),
  ('Blackberry', 'knights_of_the_wall', 'moderate'),
  ('Blackberry', 'mitochondria_boosters', 'moderate'),
  ('Blueberry', 'knights_of_the_wall', 'moderate'),
  ('Blueberry', 'mitochondria_boosters', 'minor'),
  ('Broccoli', 'vitamin_lab', 'moderate'),
  ('Brown rice', 'anti_inflammatory_arsenal', 'moderate'),
  ('Brown rice', 'locksmith', 'moderate'),
  ('Carrot', 'anti_inflammatory_arsenal', 'moderate'),
  ('Chia seed', 'anti_inflammatory_arsenal', 'moderate'),
  ('Chickpea', 'base_layer', 'moderate'),
  ('Chicory root', 'base_layer', 'primary'),
  ('Chicory root', 'recycling_engine', 'minor'),
  ('Concord grape', 'knights_of_the_wall', 'primary'),
  ('Cranberry', 'knights_of_the_wall', 'primary'),
  ('Flaxseed', 'anti_inflammatory_arsenal', 'moderate'),
  ('Flaxseed', 'tumor_preventors', 'primary'),
  ('Garlic', 'base_layer', 'primary'),
  ('Garlic', 'recycling_engine', 'minor'),
  ('Green banana', 'anti_inflammatory_arsenal', 'moderate'),
  ('Green banana', 'locksmith', 'primary'),
  ('Green tea', 'knights_of_the_wall', 'primary'),
  ('Jerusalem artichoke', 'base_layer', 'primary'),
  ('Kale', 'vitamin_lab', 'moderate'),
  ('Leek', 'base_layer', 'moderate'),
  ('Lentil', 'base_layer', 'moderate'),
  ('Lentil', 'locksmith', 'minor'),
  ('Miso', 'estrogen_regulators', 'moderate'),
  ('Natto', 'estrogen_regulators', 'primary'),
  ('Natto', 'vitamin_lab', 'moderate'),
  ('Oats', 'anti_inflammatory_arsenal', 'primary'),
  ('Oats', 'appetite_crew', 'primary'),
  ('Oats', 'locksmith', 'minor'),
  ('Oats', 'mood_regulators', 'moderate'),
  ('Okra', 'anti_inflammatory_arsenal', 'moderate'),
  ('Onion', 'base_layer', 'primary'),
  ('Onion', 'recycling_engine', 'minor'),
  ('Orange', 'anti_inflammatory_arsenal', 'minor'),
  ('Oyster mushroom', 'appetite_crew', 'moderate'),
  ('Parsley', 'vitamin_lab', 'minor'),
  ('Pear', 'anti_inflammatory_arsenal', 'moderate'),
  ('Pomegranate', 'knights_of_the_wall', 'primary'),
  ('Pomegranate', 'mitochondria_boosters', 'primary'),
  ('Potato', 'anti_inflammatory_arsenal', 'moderate'),
  ('Potato', 'locksmith', 'moderate'),
  ('Pumpkin seed', 'mood_regulators', 'moderate'),
  ('Purple sweet potato', 'knights_of_the_wall', 'moderate'),
  ('Raspberry', 'knights_of_the_wall', 'moderate'),
  ('Raspberry', 'mitochondria_boosters', 'moderate'),
  ('Romaine lettuce', 'vitamin_lab', 'moderate'),
  ('Rye', 'appetite_crew', 'moderate'),
  ('Rye', 'tumor_preventors', 'moderate'),
  ('Sesame seed', 'mood_regulators', 'moderate'),
  ('Sesame seed', 'tumor_preventors', 'moderate'),
  ('Shallot', 'base_layer', 'moderate'),
  ('Shiitake mushroom', 'appetite_crew', 'moderate'),
  ('Soybean', 'base_layer', 'moderate'),
  ('Soybean', 'estrogen_regulators', 'primary'),
  ('Soybean', 'mood_regulators', 'moderate'),
  ('Spinach', 'stone_breakers', 'moderate'),
  ('Spinach', 'vitamin_lab', 'moderate'),
  ('Spring onion', 'base_layer', 'minor'),
  ('Strawberry', 'mitochondria_boosters', 'moderate'),
  ('Sunflower seed', 'mood_regulators', 'moderate'),
  ('Swiss chard', 'stone_breakers', 'moderate'),
  ('Swiss chard', 'vitamin_lab', 'minor'),
  ('Tempeh', 'estrogen_regulators', 'primary'),
  ('Tofu', 'estrogen_regulators', 'moderate'),
  ('Tofu', 'mood_regulators', 'moderate'),
  ('Walnut', 'mitochondria_boosters', 'primary'),
  ('White mushroom', 'appetite_crew', 'moderate'),
  ('Whole wheat', 'appetite_crew', 'moderate'),
  ('Whole wheat', 'base_layer', 'minor')
) as v(food, guild, relevance)
join foods fo on fo.canonical_name = v.food
join guilds g on g.internal_name = v.guild
on conflict (food_id, guild_id) do update set relevance = excluded.relevance;

-- ---- curiosity_facts — no natural key in schema; delete+insert (idempotent,
--      supersedes demo rows). Curated, not runtime-generated (CLAUDE.md #9).
delete from curiosity_facts;
insert into curiosity_facts (fact_text, topic_tags, confidence_tag) values
  ('Your gut hosts roughly as many microbial cells as you have human ones — you are, charitably, half you.', array['gut','microbiome'], 'solid'),
  ('People who eat 30 or more different plants a week host measurably more diverse gut microbes than people who eat 10, no matter how "healthy" those 10 are.', array['gut','variety'], 'solid'),
  ('Your microbes make most of your body''s serotonin down in the gut — the plants you feed them are part of that supply chain.', array['gut','microbiome'], 'emerging'),
  ('Fibre isn''t one thing — there are dozens of types, and different microbes specialise in different ones. Variety literally feeds a wider crew.', array['gut','variety','fiber'], 'solid'),
  ('Garlic''s inulin survives cooking — roasted whole heads are still a feast for your fibre-fermenting crews.', array['garlic'], 'solid'),
  ('Onions keep most of their quercetin in the outer layers — peel gently and you keep the good part.', array['onion'], 'solid'),
  ('A leek''s white base is where the fructans hide — the part people trim off is the prebiotic part.', array['leek'], 'solid'),
  ('Cooking tomatoes doesn''t destroy lycopene — it concentrates it. Sauce is a feature, not a compromise.', array['tomato'], 'solid'),
  ('Cooled potatoes grow resistant starch as they chill — potato salad genuinely feeds different microbes than hot mash.', array['potato','resistant starch'], 'solid'),
  ('The same trick works with rice: cook it, cool it overnight, and some starch re-crystallises into microbe food.', array['brown rice','rice'], 'solid'),
  ('A green banana and a ripe banana are almost different foods to your gut — the greener one carries far more resistant starch.', array['green banana','banana'], 'solid'),
  ('Chewing broccoli is what activates its most-studied compound — the enzyme only meets its target when you break the cells.', array['broccoli'], 'emerging'),
  ('Kale, cabbage, and Brussels sprouts are all the same species — Brassica oleracea, bred into wildly different shapes.', array['kale','cabbage','brussels sprouts','broccoli','cauliflower'], 'solid'),
  ('Beetroot''s colour is betalain, and it''s doing more than staining your fingers — that pigment is the point.', array['beet'], 'emerging'),
  ('Half an avocado has more fibre than two slices of wholemeal bread — a fruit that eats like a fat.', array['avocado'], 'solid'),
  ('Raspberries carry around eight grams of fibre per cup — one of the highest of any fruit you can buy.', array['raspberry'], 'solid'),
  ('Pomegranate feeds a compound called urolithin A that only certain people''s microbes can make — eat it and find out if you''re one.', array['pomegranate'], 'emerging'),
  ('The ellagitannins in walnuts get converted by gut bacteria into the same urolithins as pomegranate — nuts and fruit, same pathway.', array['walnut'], 'emerging'),
  ('Oats owe their reputation to beta-glucan, a soluble fibre your microbes ferment into compounds that talk to the rest of your body.', array['oats','barley'], 'emerging'),
  ('Chicory root is where most supplement-bottle inulin actually comes from — the plant version is the original.', array['chicory root'], 'solid'),
  ('Jerusalem artichokes are so rich in inulin they''re nicknamed "fartichokes" — start with a small amount and let your microbes adjust.', array['jerusalem artichoke'], 'solid'),
  ('Turmeric''s curcumin is poorly absorbed on its own, but a crack of black pepper can help it along.', array['turmeric','black pepper'], 'emerging'),
  ('Herbs punch far above their weight — oregano and thyme carry some of the densest polyphenol loads in the kitchen.', array['oregano','thyme','basil','rosemary'], 'solid'),
  ('A handful of fresh herbs counts as a plant toward your 30 — parsley isn''t just a garnish.', array['parsley','cilantro','basil','mint'], 'solid'),
  ('Fermented foods can carry billions of live microbes per serving — kimchi and kefir are crews you can eat.', array['kimchi','sauerkraut','kefir','yogurt','miso'], 'emerging'),
  ('Miso goes in after the heat is off — boiling water kills the very cultures you added it for.', array['miso'], 'solid'),
  ('Real sourdough is fermented dough — the long rise is bacteria and wild yeast pre-digesting the flour for you.', array['sourdough bread'], 'emerging'),
  ('Flaxseeds pass straight through you whole — grind them first, or their lignans stay locked inside.', array['flaxseed'], 'solid'),
  ('Chia''s magic is mucilage, the gel it forms in water — a soluble fibre your butyrate-makers love.', array['chia seed'], 'solid'),
  ('Berries get their deep blues and purples from anthocyanins, the same pigments that feed your gut''s barrier-guarding crews.', array['blueberry','blackberry','raspberry'], 'emerging'),
  ('Eating an orange beats drinking it — the fibre and much of the hesperidin live in the segments and pith.', array['orange'], 'solid'),
  ('Mushrooms aren''t plants, but their beta-glucans still count toward the diversity your microbes crave.', array['white mushroom','shiitake mushroom','oyster mushroom'], 'solid'),
  ('Seaweed carries fibres — like fucoidan — that simply don''t exist in land plants. A different feed entirely.', array['nori','wakame','kombu'], 'emerging'),
  ('Lentils cook in 25 minutes with no soaking and deliver GOS, one of the top bacterial fuels going.', array['lentil','chickpea'], 'solid'),
  ('The skin is where a lot of the action is — apples, grapes, and aubergines keep their best compounds just under the peel.', array['apple','grape','eggplant'], 'solid');

-- ---- success_stories — delete+insert (idempotent). Truthful + representative;
--      no cherry-picked medical claims (SPEC §2). verified=false until real quote.
delete from success_stories;
insert into success_stories (text, attribution, verified) values
  ('Eating across more colors each week made hitting 30 plants feel like collecting, not a chore.', 'Early tester (representative)', false),
  ('I never knew how few different plants I was eating until the weekly count showed me. Now I hit thirty most weeks.', 'Early tester (representative)', false),
  ('The garden blooming when I kept feeding the same crews made the science click in a way a chart never did.', 'Early tester (representative)', false),
  ('The quiet heads-up that one food kept showing up on my rough days helped me spot a pattern I had missed for years.', 'Early tester (representative)', false),
  ('Snapping a photo instead of weighing and typing meant I actually kept logging past week one.', 'Early tester (representative)', false),
  ('Watching my energy trend up as my plant count grew was the nudge that kept me going.', 'Early tester (representative)', false);
