-- =====================================================================
-- 20260701000005_seed_singlemode.sql  —  single-mode content seed
-- GENERATED from /data/worlds.csv, recipes.csv, tutorial_steps.csv by
-- /data/build_seed_sql.py. Do not hand-edit; edit the CSVs + regenerate.
-- Idempotent (ON CONFLICT / delete+insert). 🔒 FENCE 4/8: claim_risk rows are
-- RD-REVIEW-REQUIRED placeholder copy. Curated, never runtime-generated (rule #9).
-- =====================================================================

-- ---- worlds — ON CONFLICT ("order") ---------------------------------
insert into worlds ("order", name, unlock_rule_key, intro_copy) values
  (1, 'The Core', 'core_default', 'The crews almost everyone hosts — your gut''s backbone. Feed them a variety of plants and watch them bloom.'),
  (2, 'The Keystone Reaches', 'world2_after_core', 'Small crews with outsized power: they crack open the tough fibers so everyone else can feed. Unlocks as your Core blooms.'),
  (3, 'The Frontier', 'world3_after_keystones', 'The crews science is still charting — mood, hormones, and more. Emerging, personal, and yours to discover.')
on conflict ("order") do update set
  name = excluded.name,
  unlock_rule_key = excluded.unlock_rule_key,
  intro_copy = excluded.intro_copy;

-- ---- districts.world_id: the existing districts all belong to World 1 (The Core)
update districts set world_id = (select id from worlds where "order" = 1);

-- ---- recipes — no natural key; delete+insert (idempotent) -----------
delete from recipes;
insert into recipes (title, description, color_ids, fiber_highlights, ingredients, steps, prep_minutes, source, claim_risk, suggest_protein) values
  ('Rainbow crunch bowl', 'A quick bowl built to hit several colours at once.', array['red','orange','green','white_brown'], 'A generous mix of gentle, varied fibres.', array['1 cup cooked quinoa','1 cup shredded red cabbage','1 medium carrot, grated','2 cups baby spinach','1/2 cup canned chickpeas, rinsed','juice of 1 lemon','1 tbsp olive oil'], array['Cook a cup of quinoa and let it cool','Shred the red cabbage and grate the carrot','Toss with baby spinach and chickpeas','Dress with lemon and olive oil'], 20, 'Curated', false, true),
  ('Overnight oats with berries', 'Beta-glucan oats plus deeply coloured berries, ready when you wake.', array['blue_purple','white_brown'], 'Oats bring beta-glucan, a well-studied prebiotic fibre.', array['1/2 cup rolled oats','1/2 cup milk of choice','1 tbsp chia seeds','3/4 cup mixed berries'], array['Combine oats and milk in a jar','Stir in the chia seeds','Top with the mixed berries','Chill overnight'], 5, 'Curated', true, false),
  ('Roasted roots medley', 'Caramelised roots for a sweet, colourful side.', array['orange','red','white_brown'], 'Cooked-then-cooled potato adds resistant starch.', array['2 medium carrots, chopped','1 medium beetroot, cubed','1 large potato, cubed','1 tbsp olive oil','pinch of salt'], array['Chop the carrots, beetroot and potato','Toss with olive oil and salt','Roast at 200C for 30 minutes','Cool slightly before serving'], 40, 'Curated', false, true),
  ('Green herb lentils', 'Earthy lentils brightened with green herbs.', array['green'], 'Lentils are rich in GOS, a top bacterial fuel.', array['1 cup dried green lentils','1/2 cup chopped parsley','2 cups baby spinach','juice of 1 lemon','1 clove garlic, minced'], array['Simmer the lentils until tender, about 25 minutes','Fold through the parsley and spinach','Finish with lemon and the minced garlic'], 30, 'Curated', true, false),
  ('Chickpea and tomato stew', 'A cosy stew leaning on legumes and colour.', array['red','orange','green'], 'Legumes bring GOS and resistant starch together.', array['1 onion, diced','2 cloves garlic, minced','1 can (400g) chopped tomatoes','1 can (400g) chickpeas, rinsed','2 cups chard, chopped','1 tbsp olive oil'], array['Saute the onion and garlic in olive oil','Add the tomatoes and chickpeas','Simmer 20 minutes','Stir through the chard until wilted'], 35, 'Curated', true, false),
  ('Purple slaw', 'A crunchy slaw in a striking colour.', array['blue_purple','white_brown'], 'Cabbage adds gentle, varied fibre.', array['3 cups shredded red cabbage','1 apple, julienned','1/2 cup plain yogurt','1 tsp mustard','pinch of salt'], array['Shred the red cabbage and julienne the apple','Whisk the yogurt and mustard with salt','Toss together and rest 10 minutes'], 15, 'Curated', true, true),
  ('Miso mushroom noodle bowl', 'Umami broth with fermented depth and beta-glucans.', array['white_brown','green'], 'Shiitake beta-glucans plus miso''s live cultures.', array['1 tbsp miso paste','2 cups warm (not boiling) water or broth','1 cup sliced shiitake mushrooms','1 cup baby bok choy, halved','1 bundle soba noodles','2 spring onions, sliced'], array['Cook the soba noodles and divide into bowls','Simmer the shiitake and bok choy in the broth 5 minutes','Take off the heat and stir in the miso until dissolved','Pour over the noodles and top with spring onion'], 20, 'Curated', true, true),
  ('Berry kefir smoothie', 'A fast probiotic-and-polyphenol breakfast in a glass.', array['blue_purple','red'], 'Kefir cultures plus berry anthocyanins.', array['1 cup plain kefir','1 cup mixed berries','1 tbsp ground flaxseed','1 small banana'], array['Add the kefir, berries, flaxseed and banana to a blender','Blend until smooth','Pour and drink fresh'], 5, 'Curated', true, false),
  ('Everyday big salad', 'A flexible plate designed to rack up plant variety fast.', array['green','red','orange','white_brown'], 'A wide spread of gentle fibres and colours.', array['3 cups mixed leaves','1 carrot, grated','1/2 red pepper, sliced','1/4 red onion, thin','1/2 cup chickpeas','handful of walnuts','1 tbsp olive oil','splash of vinegar'], array['Pile the mixed leaves into a big bowl','Add the carrot, pepper, onion and chickpeas','Scatter the walnuts','Dress with olive oil and vinegar'], 10, 'Curated', false, true),
  ('Warm barley and roasted veg', 'A hearty grain bowl that keeps its fibre.', array['orange','green','white_brown'], 'Barley beta-glucan with roasted-veg polyphenols.', array['1 cup cooked pearl barley','1 cup butternut squash, cubed','1 cup broccoli florets','1/2 red onion, wedged','1 tbsp olive oil','handful of parsley'], array['Roast the squash, broccoli and onion at 200C for 25 minutes','Cook the barley separately','Fold the veg through the warm barley','Finish with chopped parsley'], 40, 'Curated', false, true),
  ('Golden turmeric dal', 'A gentle yellow lentil stew with warm spices.', array['yellow','orange','white_brown'], 'Red lentils bring GOS; turmeric rides along with black pepper.', array['1 cup red lentils','1 tsp ground turmeric','1 tsp cumin seeds','1 onion, diced','2 cloves garlic, minced','1 carrot, diced','crack of black pepper','3 cups water'], array['Saute the onion, garlic and cumin until soft','Add the lentils, carrot, turmeric and water','Simmer 25 minutes until creamy','Finish with black pepper'], 35, 'Curated', true, false),
  ('Mango pineapple sunshine smoothie', 'A yellow-orange blast for the colors most weeks miss.', array['yellow','orange'], 'Fruit fibre plus a spoon of chia for the gel.', array['1 cup frozen mango chunks','1/2 cup pineapple chunks','1 small banana','1 tbsp chia seeds','1 cup water or milk of choice'], array['Add everything to a blender','Blend until smooth','Let sit 2 minutes so the chia thickens'], 5, 'Curated', false, false),
  ('Corn and yellow pepper salsa', 'A bright scoopable side that covers yellow in one bowl.', array['yellow','red','green'], 'Corn kernels keep their fibre in the skins.', array['1 cup corn kernels','1 yellow pepper, diced','1 tomato, diced','1/4 red onion, minced','handful of cilantro, chopped','juice of 1 lime'], array['Char the corn in a dry pan for 3 minutes','Mix with the pepper, tomato and onion','Fold in the cilantro and lime'], 10, 'Curated', false, true),
  ('Kimchi fried rice', 'Day-old rice plus kimchi — resistant starch meets live cultures.', array['white_brown','green','red'], 'Cooled rice adds resistant starch; kimchi brings the ferment.', array['2 cups cooked and cooled rice','1 cup kimchi, chopped','2 spring onions, sliced','1 tbsp sesame oil','1 tsp soy sauce'], array['Heat the sesame oil in a wide pan','Fry the rice until it crisps at the edges','Fold in the kimchi and warm through, do not boil','Top with spring onion and soy sauce'], 15, 'Curated', true, true),
  ('Avocado toast on sourdough', 'The classic, upgraded with seeds and pepper.', array['green','white_brown'], 'Sourdough''s long ferment plus avocado''s fibre.', array['2 slices sourdough bread','1 ripe avocado','1 tbsp pumpkin seeds','pinch of chili flakes','squeeze of lemon'], array['Toast the sourdough','Mash the avocado with lemon','Spread, then scatter seeds and chili flakes'], 8, 'Curated', true, true),
  ('Crispy roasted chickpeas', 'A crunchy snack jar that feeds the deep-fibre crews.', array['white_brown','orange'], 'Chickpeas carry GOS and resistant starch even when roasted.', array['1 can (400g) chickpeas, rinsed and dried','1 tbsp olive oil','1 tsp smoked paprika','1/2 tsp cumin','pinch of salt'], array['Pat the chickpeas very dry','Toss with oil and spices','Roast at 200C for 25 minutes, shaking once','Cool until crisp'], 30, 'Curated', true, false),
  ('Berry walnut yogurt bowl', 'Probiotic base, polyphenol toppings, thirty seconds of work.', array['blue_purple','red','white_brown'], 'Live-culture yogurt plus berry anthocyanins and walnut fibre.', array['1 cup plain live yogurt','3/4 cup mixed berries','small handful of walnuts','1 tsp honey (optional)','1 tbsp ground flaxseed'], array['Spoon the yogurt into a bowl','Top with berries, walnuts and flaxseed','Drizzle the honey if you like'], 3, 'Curated', true, false),
  ('Sheet-pan ratatouille', 'Five plants roasting themselves while you do something else.', array['red','blue_purple','green','orange'], 'A wide mix of gentle vegetable fibres and polyphenols.', array['1 eggplant, cubed','1 zucchini, sliced','1 red pepper, sliced','1 red onion, wedged','2 tomatoes, quartered','2 cloves garlic, whole','2 tbsp olive oil','1 tsp dried oregano'], array['Toss everything on a sheet pan with the oil and oregano','Roast at 200C for 35 minutes, turning once','Rest 5 minutes before serving'], 45, 'Curated', false, true);

-- ---- tutorial_steps — DELETE-then-insert so the CSV is authoritative
--      (upsert alone leaves removed/renumbered steps behind — coach rework,
--      2026-07-09). tutorial_state (completions) is unaffected: it stores
--      section_key as text, not an FK to this table.
delete from tutorial_steps;
insert into tutorial_steps (section_key, "order", title, body, target_hint, claim_risk) values
  ('intro', 0, 'Here''s how it works', 'Hi, I''m {gardener} — your gut gardener. You''ve seen the why and the catch; my job is the how. Snap your plates and I''ll grow your garden while keeping your fiber at a pace your gut is happy with. Quick tour?', 'home', false),
  ('intro', 1, 'Your dashboard', 'Home base: the week''s plant count, the rainbow, and the 3 P''s, with callouts for exactly what to eat to fill today''s gaps. Thirty different plants a week is the target — variety, never restriction.', 'dashboard', true),
  ('intro', 2, 'The 3 P''s', 'Three things a well-fed gut loves each day: Prebiotic (fiber your microbes eat), Probiotic (live cultures, like yogurt or kimchi), and Polyphenol (deep-colored plant compounds). Tap the pill any time for your trend.', 'threeps', true),
  ('intro', 3, 'Snap your meals', 'Point the camera at your plate and I''ll spot the plants and feed your garden — no weighing, no typing. A quick note like "extra onion" catches what the camera can''t see.', 'snap', false),
  ('intro', 4, 'Your fiber goal is coming', 'Remember the catch — too much fiber too fast backfires. So there''s no number in week one: I watch how you actually eat, then unlock a goal that''s comfortable for you and raise it gently, water reminders included.', 'fiber', true),
  ('intro', 5, 'Eat freely — I''ve got the rest', 'The part I care about most. The optional check-in plus my quiet watching notice what sits well and what doesn''t — and I''ll always ask before flagging anything. Over time I steer you toward the foods that make you feel good.', 'checkin', true),
  ('garden', 0, 'Your living map', 'This whole world is your garden, and it grows as you feed it. Drag to roam, pinch to zoom — each region is a district of microbe crews your plants feed.', 'garden', true),
  ('garden', 1, 'Locked lands', 'Foggy regions are still sealed. Keep feeding your crews and new districts — even whole new worlds — open up. Tap any bloomed guild to meet the microbes behind it.', 'garden', true),
  ('garden', 2, 'Rhythm beats feasts', 'Steady, varied feeding makes a guild bloom and hold; a single feast then nothing lets it fade. A little of many plants, most days, is the whole trick.', 'garden', true),
  ('rainbow', 0, 'Eat the rainbow', 'Six color groups, each carrying its own phytochemicals. Any amount counts toward the week''s six — a ring closes fully when you eat a lot of that color, and the outline shows how much is left to fill.', 'rainbow', true),
  ('rainbow', 1, 'Tap a color', 'Each color''s page shows its week, example foods, and what it does for you — the fastest way to answer "what should I add today?"', 'rainbow', true),
  ('plants', 0, 'Your plant field guide', 'Every new plant you eat joins your collection for life — rarer finds are a bigger deal. Tap any plant to read its story.', 'plants', false),
  ('fermented', 0, 'Fermented finds', 'Fermented foods bring live cultures — the probiotic P. A little each day is a lovely habit, and each find is collected here.', 'fermented', true),
  ('phytochemicals', 0, 'Phytochemicals', 'The compounds behind the colors — your microbes turn them into useful things. The coverage bars show how much of the catalogue you''ve eaten this week, fortnight, and month.', 'phytochemicals', true),
  ('phytochemicals', 1, 'Chase the gaps', 'Tap a coverage bar to see exactly which compounds you haven''t had lately — each one lists the foods that carry it.', 'phytochemicals', false),
  ('yourfiber', 0, 'Fast fibers, slow fibers', 'Fast-fermenting fibers get devoured by your microbes within hours; slower ones burn all day. Fast fuel grows the garden quickest — and makes the most gas while your crews scale up. These charts show your mix.', 'yourfiber', true),
  ('yourfiber', 1, 'Your gut adapts', 'Feed a crew steadily and it grows capacity — meals that felt lively a month ago sit quietly once the microbes that eat them multiply. Slow, steady increases are the whole trick.', 'yourfiber', true),
  ('customize', 0, 'Make your check-in yours', 'Toggle any of these on or off — track as much or as little as you like. What you keep is exactly what {gardener} asks each day, and it shapes your trends too.', 'customize', false)
on conflict (section_key, "order") do update set
  title = excluded.title,
  body = excluded.body,
  target_hint = excluded.target_hint,
  claim_risk = excluded.claim_risk;
