-- =====================================================================
-- 20260625000010_seed_real.sql  —  Module G real seed dataset (STAGED)
-- GENERATED from /data/*.csv by /data/build_seed_sql.py. Do not hand-edit;
-- edit the CSVs (the reviewable source of truth) and regenerate.
--
-- Idempotent + supersedes the Phase-0 demo seed (...000003) via
-- INSERT ... ON CONFLICT (<natural key>) DO UPDATE. Safe to re-run.
-- Natural keys: colors.id | fibers/plants/phytochemicals.name |
--   districts.order | guilds.internal_name | foods.canonical_name |
--   junctions composite PK | fodmap_profiles.food_id.
--
-- 🔒 FENCE 2 (SPEC §14): guilds.claim_risk=true on Mood/Estrogen/Mitochondria/
--   Tumor names; substantiation is RD-REVIEW-REQUIRED placeholder copy.
-- 🔒 FENCE 4 (SPEC §14): fodmap_profiles + food_fibers.est_grams_per_serving are
--   REVERSE-ENGINEERED / COARSE placeholders. OWNER: validate FODMAP source
--   LICENSING (e.g. Monash) before launch. Never surface as measured grams.
-- Sources cited per-file in /data/*.csv (USDA FoodData Central; USDA flavonoid
--   tables; Phenol-Explorer; framework §4-5).
-- Supabase applies each migration file inside its own transaction, so this
-- file omits an explicit BEGIN/COMMIT (matches the repo's other migrations).
-- =====================================================================

-- ---- colors (rainbow groups) — ON CONFLICT (id) ----------------------
insert into colors (id, meaning_copy, what_it_does_copy) values
  ('red', 'Lycopene, anthocyanins and ellagic acid', 'Polyphenols linked to heart and circulation; some feed mucus-barrier crews'),
  ('orange', 'Alpha- and beta-carotene', 'Carotenoids the body can turn into vitamin A for eyes, skin and immune signalling'),
  ('yellow', 'Flavonoids, lutein and zeaxanthin', 'A broad antioxidant mix; lutein and zeaxanthin concentrate in the eye'),
  ('green', 'Chlorophyll, folate and lutein', 'Folate supports methylation; chlorophyll and glucosinolates ride along in leafy and cruciferous greens'),
  ('blue_purple', 'Anthocyanins', 'Deep-pigment polyphenols that reach the colon and feed barrier-keeping bacteria like Akkermansia'),
  ('white_brown', 'Organosulfur compounds and quercetin', 'Allium sulfur compounds and prebiotic fibers; the fuel layer for your Base Layer bifidobacteria')
on conflict (id) do update set
  meaning_copy = excluded.meaning_copy,
  what_it_does_copy = excluded.what_it_does_copy;

-- ---- fibers — ON CONFLICT (name) -------------------------------------
insert into fibers (name, is_fodmap_trigger, notes) values
  ('inulin', true, 'Fructan. Top bacterial fuel AND classic IBS trigger. Chicory, jerusalem artichoke, onion, garlic.'),
  ('fos', true, 'Fructo-oligosaccharide; shorter-chain fructan, distinct from inulin. Onion, garlic, asparagus.'),
  ('gos', true, 'Galacto-oligosaccharide. Legumes and some dairy. A FODMAP trigger.'),
  ('rs2', false, 'Resistant starch, native granular form. Green banana, raw potato starch, legumes.'),
  ('rs3', false, 'Retrograded resistant starch, formed when cooked starch is cooled. Cooled rice and potato.'),
  ('pectin', false, 'Soluble, gentle, gel-forming. Apple, citrus, carrot. Feeds butyrate producers.'),
  ('beta_glucan', false, 'Soluble fiber of oats, barley and mushrooms. Feeds propionate producers; lowers cholesterol.'),
  ('arabinoxylan', false, 'Major fiber of whole wheat, rye and bran. Commonly overlooked; feeds Base Layer and Appetite Crew.'),
  ('psyllium', false, 'Husk fiber. Poorly fermented, so it bulks mechanically rather than feeding much.'),
  ('mucilage', false, 'Gel fiber of chia, flax and okra. Fermentable; soothes and feeds butyrate producers.')
on conflict (name) do update set
  is_fodmap_trigger = excluded.is_fodmap_trigger,
  notes = excluded.notes;

-- ---- phytochemicals — ON CONFLICT (name); maps_to_color after colors -
insert into phytochemicals (name, class, maps_to_color_id) values
  ('beta_carotene', 'carotenoid'::phyto_class, 'orange'::color_name),
  ('alpha_carotene', 'carotenoid'::phyto_class, 'orange'::color_name),
  ('lycopene', 'carotenoid'::phyto_class, 'red'::color_name),
  ('lutein', 'carotenoid'::phyto_class, 'green'::color_name),
  ('zeaxanthin', 'carotenoid'::phyto_class, 'yellow'::color_name),
  ('beta_cryptoxanthin', 'carotenoid'::phyto_class, 'orange'::color_name),
  ('anthocyanin', 'polyphenol'::phyto_class, 'blue_purple'::color_name),
  ('quercetin', 'polyphenol'::phyto_class, 'yellow'::color_name),
  ('kaempferol', 'polyphenol'::phyto_class, 'yellow'::color_name),
  ('catechin', 'polyphenol'::phyto_class, 'green'::color_name),
  ('epigallocatechin_gallate', 'polyphenol'::phyto_class, 'green'::color_name),
  ('ellagic_acid', 'polyphenol'::phyto_class, 'red'::color_name),
  ('resveratrol', 'polyphenol'::phyto_class, 'blue_purple'::color_name),
  ('hesperidin', 'polyphenol'::phyto_class, 'orange'::color_name),
  ('naringenin', 'polyphenol'::phyto_class, 'yellow'::color_name),
  ('curcumin', 'polyphenol'::phyto_class, 'yellow'::color_name),
  ('chlorogenic_acid', 'polyphenol'::phyto_class, 'white_brown'::color_name),
  ('punicalagin', 'polyphenol'::phyto_class, 'red'::color_name),
  ('genistein', 'polyphenol'::phyto_class, 'white_brown'::color_name),
  ('secoisolariciresinol', 'polyphenol'::phyto_class, 'white_brown'::color_name),
  ('allicin', 'organosulfur'::phyto_class, 'white_brown'::color_name),
  ('sulforaphane', 'organosulfur'::phyto_class, 'green'::color_name),
  ('glucosinolate', 'organosulfur'::phyto_class, 'green'::color_name),
  ('s_allyl_cysteine', 'organosulfur'::phyto_class, 'white_brown'::color_name),
  ('limonene', 'terpene'::phyto_class, 'orange'::color_name),
  ('carnosic_acid', 'terpene'::phyto_class, 'green'::color_name),
  ('beta_sitosterol', 'phytosterol'::phyto_class, 'white_brown'::color_name),
  ('soyasaponin', 'saponin'::phyto_class, 'white_brown'::color_name),
  ('piperine', 'alkaloid'::phyto_class, 'white_brown'::color_name),
  ('capsaicin', 'alkaloid'::phyto_class, 'red'::color_name),
  ('chlorophyll', 'chlorophyll'::phyto_class, 'green'::color_name),
  ('betanin', 'betalain'::phyto_class, 'red'::color_name)
on conflict (name) do update set
  class = excluded.class,
  maps_to_color_id = excluded.maps_to_color_id;

-- ---- districts — ON CONFLICT ("order") ------------------------------
insert into districts ("order", name, unlock_rule_key) values
  (1, 'The Backbone District', 'tier2_unlocked'),
  (2, 'The Keystones', 'two_backbone_blooming'),
  (3, 'The Scientists', 'one_keystone_blooming_and_10_days'),
  (4, 'The Hidden Gems', 'after_d3_engagement')
on conflict ("order") do update set
  name = excluded.name,
  unlock_rule_key = excluded.unlock_rule_key;

-- ---- guilds — ON CONFLICT (internal_name); Fence 2 claim_risk -------
insert into guilds (district_id, internal_name, display_name, function_copy, confidence_tag, feeds_copy, claim_risk, substantiation)
select d.id, v.internal_name, v.display_name, v.function_copy, v.confidence_tag::confidence_tag, v.feeds_copy, v.claim_risk, v.substantiation
from (values
  (1, 'anti_inflammatory_arsenal', 'The Anti-inflammatory Arsenal', 'Butyrate producers (Faecalibacterium, Roseburia) that fuel the gut lining and calm inflammation. The backbone.', 'solid', 'Resistant starch, pectin, beta-glucan, oats and beans', false, null),
  (1, 'appetite_crew', 'The Appetite Crew', 'Propionate producers (Bacteroides) tied to satiety, steadier blood sugar and lower cholesterol.', 'solid', 'Beta-glucan, barley, arabinoxylan and seaweed', false, null),
  (1, 'base_layer', 'The Base Layer', 'Bifidobacteria that acidify the gut, crowd out pathogens and feed everyone else. Base of the pyramid.', 'solid', 'Inulin, FOS and GOS — onion, garlic, chicory and legumes', false, null),
  (1, 'recycling_engine', 'The Recycling Engine', 'Lactate utilizers (Anaerostipes, E. hallii) that turn lactate into more butyrate and keep the system stable.', 'solid', 'Indirect — they eat what the Base Layer makes, so feed the Base Layer', false, null),
  (2, 'locksmith', 'The Locksmith', 'Ruminococcus bromii — cracks open resistant-starch particles so everyone else can feed. Without it, RS passes straight through.', 'solid', 'Resistant starch — green banana, cooled rice and potato', false, null),
  (2, 'knights_of_the_wall', 'The Knights of the Wall', 'Akkermansia muciniphila — maintains the mucus barrier and tracks with metabolic health.', 'maturing', 'Polyphenols — cranberry, pomegranate, green tea and concord grape', false, null),
  (3, 'vitamin_lab', 'The Vitamin Lab', 'Vitamin synthesizers that produce K2, folate, biotin and B12. Where your 30-plants number cashes out into a mechanism.', 'solid', 'Overall diversity — the wider your plant range, the busier this lab', false, null),
  (3, 'mood_regulators', 'The Mood Regulators', 'Tryptophan and indole producers on the gut-brain axis; ties to the mood dashboard.', 'frontier', 'Tryptophan-rich foods (oats, seeds, soy) plus fiber', true, '[emerging science] RD-REVIEW-REQUIRED: gut-brain axis is a real and active research field, but a direct food→mood causal claim is unproven in humans. Frame as association only; never imply the app treats mood. Pending RD sign-off.'),
  (4, 'estrogen_regulators', 'The Estrogen Regulators', 'Equol producers from soy isoflavones; roughly 1 in 3 people host them. Equol is a potent phytoestrogen of cardiovascular, bone and menopause interest.', 'emerging', 'Soy isoflavones — soybean, tempeh, tofu and miso', true, '[emerging science] RD-REVIEW-REQUIRED: equol-producer status is a real metabotype confirmed only by a urine test after a soy challenge, not by tracking intake. Phytoestrogen health effects are emerging, not established. No therapeutic claim. Pending RD sign-off.'),
  (4, 'mitochondria_boosters', 'The Mitochondria Boosters', 'Urolithin producers from ellagitannins; metabotypes A/B/0. Urolithin A is studied for mitochondrial and muscle health.', 'emerging', 'Pomegranate, walnuts and berries', true, '[emerging science] RD-REVIEW-REQUIRED: urolithin-A benefits rest on early human trials and supplement studies, not whole-food outcomes. Producer status is a metabotype, not guaranteed by intake. No therapeutic claim. Pending RD sign-off.'),
  (4, 'tumor_preventors', 'The Tumor Preventors', 'Enterolignan producers from plant lignans; enterolactone is of hormonal and cardiovascular interest.', 'associational', 'Flax, sesame and rye', true, '[emerging science] RD-REVIEW-REQUIRED: ASSOCIATIONAL ONLY — NOT proven cancer prevention. Cancer-prevention claims are heavily scrutinized by FDA/FTC and app-store review. Name is placeholder; likely must be softened before launch. Pending RD sign-off.'),
  (4, 'stone_breakers', 'The Stone Breakers', 'Oxalate degraders (Oxalobacter) — niche, but a clean food→function link that matters mainly for kidney-stone formers.', 'solid', 'Niche — they process oxalate from foods like spinach, beet and almond', false, null)
) as v(district_order, internal_name, display_name, function_copy, confidence_tag, feeds_copy, claim_risk, substantiation)
join districts d on d."order" = v.district_order
on conflict (internal_name) do update set
  district_id = excluded.district_id,
  display_name = excluded.display_name,
  function_copy = excluded.function_copy,
  confidence_tag = excluded.confidence_tag,
  feeds_copy = excluded.feeds_copy,
  claim_risk = excluded.claim_risk,
  substantiation = excluded.substantiation;

-- ---- plants — ON CONFLICT (name) ------------------------------------
insert into plants (name, scientific_name, plant_family, rarity_tier) values
  ('Garlic', 'Allium sativum', 'Amaryllidaceae', 'common'),
  ('Onion', 'Allium cepa', 'Amaryllidaceae', 'common'),
  ('Leek', 'Allium ampeloprasum', 'Amaryllidaceae', 'uncommon'),
  ('Shallot', 'Allium cepa var. aggregatum', 'Amaryllidaceae', 'uncommon'),
  ('Spring onion', 'Allium fistulosum', 'Amaryllidaceae', 'common'),
  ('Chives', 'Allium schoenoprasum', 'Amaryllidaceae', 'uncommon'),
  ('Broccoli', 'Brassica oleracea var. italica', 'Brassicaceae', 'common'),
  ('Cauliflower', 'Brassica oleracea var. botrytis', 'Brassicaceae', 'common'),
  ('Cabbage', 'Brassica oleracea var. capitata', 'Brassicaceae', 'common'),
  ('Kale', 'Brassica oleracea var. sabellica', 'Brassicaceae', 'uncommon'),
  ('Brussels sprouts', 'Brassica oleracea var. gemmifera', 'Brassicaceae', 'uncommon'),
  ('Bok choy', 'Brassica rapa subsp. chinensis', 'Brassicaceae', 'uncommon'),
  ('Arugula', 'Eruca vesicaria', 'Brassicaceae', 'uncommon'),
  ('Radish', 'Raphanus sativus', 'Brassicaceae', 'common'),
  ('Turnip', 'Brassica rapa subsp. rapa', 'Brassicaceae', 'uncommon'),
  ('Watercress', 'Nasturtium officinale', 'Brassicaceae', 'rare'),
  ('Spinach', 'Spinacia oleracea', 'Amaranthaceae', 'common'),
  ('Romaine lettuce', 'Lactuca sativa', 'Asteraceae', 'common'),
  ('Swiss chard', 'Beta vulgaris subsp. vulgaris', 'Amaranthaceae', 'rare'),
  ('Collard greens', 'Brassica oleracea var. viridis', 'Brassicaceae', 'uncommon'),
  ('Carrot', 'Daucus carota', 'Apiaceae', 'common'),
  ('Beet', 'Beta vulgaris', 'Amaranthaceae', 'uncommon'),
  ('Sweet potato', 'Ipomoea batatas', 'Convolvulaceae', 'uncommon'),
  ('Potato', 'Solanum tuberosum', 'Solanaceae', 'common'),
  ('Parsnip', 'Pastinaca sativa', 'Apiaceae', 'rare'),
  ('Ginger', 'Zingiber officinale', 'Zingiberaceae', 'uncommon'),
  ('Turmeric', 'Curcuma longa', 'Zingiberaceae', 'rare'),
  ('Jerusalem artichoke', 'Helianthus tuberosus', 'Asteraceae', 'legendary'),
  ('Chicory root', 'Cichorium intybus', 'Asteraceae', 'legendary'),
  ('Pumpkin', 'Cucurbita pepo', 'Cucurbitaceae', 'uncommon'),
  ('Butternut squash', 'Cucurbita moschata', 'Cucurbitaceae', 'uncommon'),
  ('Zucchini', 'Cucurbita pepo var. cylindrica', 'Cucurbitaceae', 'common'),
  ('Cucumber', 'Cucumis sativus', 'Cucurbitaceae', 'common'),
  ('Tomato', 'Solanum lycopersicum', 'Solanaceae', 'common'),
  ('Bell pepper', 'Capsicum annuum', 'Solanaceae', 'common'),
  ('Eggplant', 'Solanum melongena', 'Solanaceae', 'uncommon'),
  ('Chili pepper', 'Capsicum annuum var. glabriusculum', 'Solanaceae', 'uncommon'),
  ('Asparagus', 'Asparagus officinalis', 'Asparagaceae', 'uncommon'),
  ('Celery', 'Apium graveolens', 'Apiaceae', 'common'),
  ('Fennel', 'Foeniculum vulgare', 'Apiaceae', 'rare'),
  ('Artichoke', 'Cynara cardunculus var. scolymus', 'Asteraceae', 'rare'),
  ('Okra', 'Abelmoschus esculentus', 'Malvaceae', 'rare'),
  ('Green pea', 'Pisum sativum', 'Fabaceae', 'common'),
  ('Corn', 'Zea mays', 'Poaceae', 'common'),
  ('Chickpea', 'Cicer arietinum', 'Fabaceae', 'uncommon'),
  ('Lentil', 'Lens culinaris', 'Fabaceae', 'uncommon'),
  ('Black bean', 'Phaseolus vulgaris', 'Fabaceae', 'uncommon'),
  ('Kidney bean', 'Phaseolus vulgaris var. nanus', 'Fabaceae', 'uncommon'),
  ('White bean', 'Phaseolus vulgaris var. albus', 'Fabaceae', 'uncommon'),
  ('Soybean', 'Glycine max', 'Fabaceae', 'uncommon'),
  ('Peanut', 'Arachis hypogaea', 'Fabaceae', 'common'),
  ('Oats', 'Avena sativa', 'Poaceae', 'common'),
  ('Barley', 'Hordeum vulgare', 'Poaceae', 'uncommon'),
  ('Brown rice', 'Oryza sativa', 'Poaceae', 'common'),
  ('Quinoa', 'Chenopodium quinoa', 'Amaranthaceae', 'uncommon'),
  ('Whole wheat', 'Triticum aestivum', 'Poaceae', 'common'),
  ('Rye', 'Secale cereale', 'Poaceae', 'rare'),
  ('Buckwheat', 'Fagopyrum esculentum', 'Polygonaceae', 'rare'),
  ('Millet', 'Panicum miliaceum', 'Poaceae', 'rare'),
  ('Sorghum', 'Sorghum bicolor', 'Poaceae', 'rare'),
  ('Almond', 'Prunus dulcis', 'Rosaceae', 'uncommon'),
  ('Walnut', 'Juglans regia', 'Juglandaceae', 'uncommon'),
  ('Cashew', 'Anacardium occidentale', 'Anacardiaceae', 'uncommon'),
  ('Pistachio', 'Pistacia vera', 'Anacardiaceae', 'uncommon'),
  ('Hazelnut', 'Corylus avellana', 'Betulaceae', 'rare'),
  ('Pecan', 'Carya illinoinensis', 'Juglandaceae', 'rare'),
  ('Brazil nut', 'Bertholletia excelsa', 'Lecythidaceae', 'rare'),
  ('Flaxseed', 'Linum usitatissimum', 'Linaceae', 'uncommon'),
  ('Chia seed', 'Salvia hispanica', 'Lamiaceae', 'uncommon'),
  ('Sesame seed', 'Sesamum indicum', 'Pedaliaceae', 'uncommon'),
  ('Sunflower seed', 'Helianthus annuus', 'Asteraceae', 'uncommon'),
  ('Pumpkin seed', 'Cucurbita pepo var. styriaca', 'Cucurbitaceae', 'uncommon'),
  ('Apple', 'Malus domestica', 'Rosaceae', 'common'),
  ('Banana', 'Musa acuminata', 'Musaceae', 'common'),
  ('Green banana', 'Musa acuminata (unripe)', 'Musaceae', 'uncommon'),
  ('Blueberry', 'Vaccinium corymbosum', 'Ericaceae', 'uncommon'),
  ('Strawberry', 'Fragaria x ananassa', 'Rosaceae', 'common'),
  ('Raspberry', 'Rubus idaeus', 'Rosaceae', 'uncommon'),
  ('Blackberry', 'Rubus fruticosus', 'Rosaceae', 'uncommon'),
  ('Orange', 'Citrus x sinensis', 'Rutaceae', 'common'),
  ('Lemon', 'Citrus x limon', 'Rutaceae', 'common'),
  ('Grape', 'Vitis vinifera', 'Vitaceae', 'common'),
  ('Concord grape', 'Vitis labrusca', 'Vitaceae', 'rare'),
  ('Pomegranate', 'Punica granatum', 'Lythraceae', 'rare'),
  ('Kiwi', 'Actinidia deliciosa', 'Actinidiaceae', 'uncommon'),
  ('Mango', 'Mangifera indica', 'Anacardiaceae', 'uncommon'),
  ('Pineapple', 'Ananas comosus', 'Bromeliaceae', 'uncommon'),
  ('Pear', 'Pyrus communis', 'Rosaceae', 'common'),
  ('Avocado', 'Persea americana', 'Lauraceae', 'uncommon'),
  ('Fig', 'Ficus carica', 'Moraceae', 'rare'),
  ('Cranberry', 'Vaccinium macrocarpon', 'Ericaceae', 'rare'),
  ('Date', 'Phoenix dactylifera', 'Arecaceae', 'uncommon'),
  ('Basil', 'Ocimum basilicum', 'Lamiaceae', 'common'),
  ('Parsley', 'Petroselinum crispum', 'Apiaceae', 'common'),
  ('Cilantro', 'Coriandrum sativum', 'Apiaceae', 'common'),
  ('Mint', 'Mentha spicata', 'Lamiaceae', 'common'),
  ('Rosemary', 'Salvia rosmarinus', 'Lamiaceae', 'uncommon'),
  ('Thyme', 'Thymus vulgaris', 'Lamiaceae', 'uncommon'),
  ('Oregano', 'Origanum vulgare', 'Lamiaceae', 'uncommon'),
  ('Cinnamon', 'Cinnamomum verum', 'Lauraceae', 'uncommon'),
  ('Nutmeg', 'Myristica fragrans', 'Myristicaceae', 'rare'),
  ('Cumin', 'Cuminum cyminum', 'Apiaceae', 'uncommon'),
  ('Black pepper', 'Piper nigrum', 'Piperaceae', 'common'),
  ('Sumac', 'Rhus coriaria', 'Anacardiaceae', 'legendary'),
  ('White mushroom', 'Agaricus bisporus', 'Agaricaceae', 'common'),
  ('Shiitake mushroom', 'Lentinula edodes', 'Omphalotaceae', 'uncommon'),
  ('Oyster mushroom', 'Pleurotus ostreatus', 'Pleurotaceae', 'rare'),
  ('Nori', 'Pyropia yezoensis', 'Bangiaceae', 'rare'),
  ('Wakame', 'Undaria pinnatifida', 'Alariaceae', 'rare'),
  ('Kombu', 'Saccharina japonica', 'Laminariaceae', 'legendary')
on conflict (name) do update set
  scientific_name = excluded.scientific_name,
  plant_family = excluded.plant_family,
  rarity_tier = excluded.rarity_tier;

-- ---- foods — ON CONFLICT (canonical_name); plant_id via plants join --
insert into foods (canonical_name, aliases, is_plant, plant_id, is_fermented, histamine_level, common_hidden_in, categories)
select v.canonical_name, v.aliases, v.is_plant, p.id, v.is_fermented, v.histamine_level::histamine_level, v.common_hidden_in, v.categories
from (values
  ('Garlic', array['garlic clove','minced garlic','ajo','garlic powder'], true, 'Garlic', false, 'low', array['curry','stir_fry','pasta_sauce','dressing','soup','marinade'], array['allium','fodmap','prebiotic']),
  ('Onion', array['yellow onion','red onion','white onion','diced onion'], true, 'Onion', false, 'low', array['curry','soup','stock','sauce','dressing','stir_fry','casserole'], array['allium','fodmap','prebiotic']),
  ('Leek', array['leeks'], true, 'Leek', false, 'low', array['soup','quiche','stock','gratin'], array['allium','fodmap','prebiotic']),
  ('Shallot', array['shallots','eschalot'], true, 'Shallot', false, 'low', array['dressing','sauce','stir_fry'], array['allium','fodmap','prebiotic']),
  ('Spring onion', array['scallion','green onion'], true, 'Spring onion', false, 'low', array['stir_fry','garnish','noodle_soup'], array['allium','fodmap']),
  ('Chives', array['chive'], true, 'Chives', false, 'low', array['garnish','dip','baked_potato'], array['allium','herb_spice']),
  ('Broccoli', array['broccoli florets','tenderstem'], true, 'Broccoli', false, 'low', '{}'::text[], array['cruciferous','green','fodmap']),
  ('Cauliflower', array['cauliflower florets'], true, 'Cauliflower', false, 'low', array['cauliflower_rice','curry'], array['cruciferous','fodmap']),
  ('Cabbage', array['green cabbage','red cabbage'], true, 'Cabbage', false, 'low', array['slaw','soup'], array['cruciferous']),
  ('Kale', array['curly kale','lacinato','cavolo nero'], true, 'Kale', false, 'low', array['smoothie','chips'], array['cruciferous','leafy_green','green']),
  ('Brussels sprouts', array['brussel sprouts'], true, 'Brussels sprouts', false, 'low', '{}'::text[], array['cruciferous','fodmap']),
  ('Bok choy', array['pak choi','chinese cabbage'], true, 'Bok choy', false, 'low', array['stir_fry'], array['cruciferous','leafy_green','green']),
  ('Arugula', array['rocket','rucola'], true, 'Arugula', false, 'low', array['salad'], array['cruciferous','leafy_green','green']),
  ('Radish', array['radishes','daikon'], true, 'Radish', false, 'low', array['salad','slaw'], array['cruciferous','root_vegetable']),
  ('Turnip', array['turnips','swede'], true, 'Turnip', false, 'low', array['soup','stew'], array['cruciferous','root_vegetable']),
  ('Watercress', array['water cress'], true, 'Watercress', false, 'low', array['salad','soup'], array['cruciferous','leafy_green','green']),
  ('Spinach', array['baby spinach','spinach leaves'], true, 'Spinach', false, 'moderate', array['curry','dip','smoothie','lasagne'], array['leafy_green','green']),
  ('Romaine lettuce', array['romaine','cos lettuce','lettuce'], true, 'Romaine lettuce', false, 'low', array['salad','wrap'], array['leafy_green','green']),
  ('Swiss chard', array['chard','silverbeet'], true, 'Swiss chard', false, 'moderate', array['saute'], array['leafy_green','green']),
  ('Collard greens', array['collards','spring greens'], true, 'Collard greens', false, 'low', array['braise'], array['cruciferous','leafy_green','green']),
  ('Carrot', array['carrots','shredded carrot','baby carrot'], true, 'Carrot', false, 'low', array['soup','stir_fry','slaw','stock','cake'], array['root_vegetable','orange']),
  ('Beet', array['beetroot','beets'], true, 'Beet', false, 'low', array['salad','juice','dip'], array['root_vegetable','red']),
  ('Sweet potato', array['sweet potatoes','yam','kumara'], true, 'Sweet potato', false, 'low', array['fries','mash','curry'], array['root_vegetable','orange']),
  ('Potato', array['potatoes','white potato','russet'], true, 'Potato', false, 'low', array['mash','fries','soup','gratin'], array['root_vegetable']),
  ('Parsnip', array['parsnips'], true, 'Parsnip', false, 'low', array['soup','roast','mash'], array['root_vegetable','white_brown']),
  ('Ginger', array['fresh ginger','ginger root'], true, 'Ginger', false, 'low', array['curry','stir_fry','marinade','smoothie','tea'], array['root_vegetable','herb_spice']),
  ('Turmeric', array['fresh turmeric','turmeric root'], true, 'Turmeric', false, 'low', array['curry','golden_milk','rice'], array['root_vegetable','herb_spice','yellow']),
  ('Jerusalem artichoke', array['sunchoke','sunroot'], true, 'Jerusalem artichoke', false, 'low', array['soup','roast'], array['root_vegetable','fodmap','prebiotic']),
  ('Chicory root', array['chicory','inulin','witloof root'], true, 'Chicory root', false, 'low', array['coffee_substitute','fiber_additive'], array['root_vegetable','fodmap','prebiotic']),
  ('Pumpkin', array['pumpkin puree','winter squash'], true, 'Pumpkin', false, 'low', array['soup','pie','curry'], array['squash','orange']),
  ('Butternut squash', array['butternut','butternut pumpkin'], true, 'Butternut squash', false, 'low', array['soup','roast','risotto'], array['squash','orange','fodmap']),
  ('Zucchini', array['courgette','summer squash'], true, 'Zucchini', false, 'low', array['fritter','ratatouille','bread'], array['squash','green']),
  ('Cucumber', array['cucumbers','gherkin'], true, 'Cucumber', false, 'low', array['salad','tzatziki'], array['squash','green']),
  ('Tomato', array['tomatoes','cherry tomato','roma'], true, 'Tomato', false, 'moderate', array['sauce','curry','salsa','soup'], array['nightshade','red']),
  ('Bell pepper', array['capsicum','sweet pepper','red pepper'], true, 'Bell pepper', false, 'low', array['stir_fry','fajita','salsa'], array['nightshade','red']),
  ('Eggplant', array['aubergine','brinjal'], true, 'Eggplant', false, 'moderate', array['curry','dip','ratatouille','moussaka'], array['nightshade','blue_purple']),
  ('Chili pepper', array['chilli','hot pepper','jalapeno'], true, 'Chili pepper', false, 'moderate', array['curry','salsa','sauce','marinade'], array['nightshade','red','herb_spice']),
  ('Asparagus', array['asparagus spears'], true, 'Asparagus', false, 'low', array['risotto','quiche'], array['fodmap','green','prebiotic']),
  ('Celery', array['celery stalk','celeriac'], true, 'Celery', false, 'low', array['soup','stock','salad','stir_fry'], array['herb_spice','green']),
  ('Fennel', array['fennel bulb','anise bulb'], true, 'Fennel', false, 'low', array['salad','roast'], array['herb_spice','white_brown']),
  ('Artichoke', array['globe artichoke','artichoke heart'], true, 'Artichoke', false, 'low', array['dip','pizza_topping'], array['fodmap','green','prebiotic']),
  ('Okra', array['okra','ladies fingers','bhindi'], true, 'Okra', false, 'low', array['gumbo','curry','stew'], array['green','fodmap']),
  ('Green pea', array['peas','garden pea','petit pois'], true, 'Green pea', false, 'low', array['soup','curry','fried_rice'], array['legume','green','fodmap']),
  ('Corn', array['sweetcorn','maize','corn kernels'], true, 'Corn', false, 'low', array['salad','soup','salsa'], array['grain','yellow']),
  ('Chickpea', array['garbanzo','hummus bean'], true, 'Chickpea', false, 'low', array['hummus','curry','falafel','soup'], array['legume','fodmap']),
  ('Lentil', array['lentils','dal','red lentil'], true, 'Lentil', false, 'low', array['dal','soup','curry','stew'], array['legume','fodmap']),
  ('Black bean', array['black beans','turtle bean'], true, 'Black bean', false, 'low', array['burrito','chili','soup'], array['legume','fodmap']),
  ('Kidney bean', array['kidney beans','rajma'], true, 'Kidney bean', false, 'low', array['chili','curry','salad'], array['legume','fodmap']),
  ('White bean', array['cannellini','navy bean','haricot'], true, 'White bean', false, 'low', array['soup','stew','dip'], array['legume','fodmap']),
  ('Soybean', array['edamame','soya bean'], true, 'Soybean', false, 'low', array['stir_fry','salad'], array['legume','soy','fodmap']),
  ('Peanut', array['peanuts','groundnut','peanut butter'], true, 'Peanut', false, 'moderate', array['satay','sauce','dressing','baked_goods'], array['legume','peanut']),
  ('Oats', array['oatmeal','rolled oats','porridge','oat'], true, 'Oats', false, 'low', array['granola','smoothie','baked_goods'], array['grain','whole_grain']),
  ('Barley', array['pearl barley','pot barley'], true, 'Barley', false, 'low', array['soup','risotto','stew'], array['grain','whole_grain','gluten','fodmap']),
  ('Brown rice', array['wholegrain rice','brown rice'], true, 'Brown rice', false, 'low', array['stir_fry','bowl','pilaf'], array['grain','whole_grain','gluten_free']),
  ('Quinoa', array['quinoa grain'], true, 'Quinoa', false, 'low', array['salad','bowl','porridge'], array['grain','whole_grain','gluten_free']),
  ('Whole wheat', array['wholemeal','whole wheat bread','wheat'], true, 'Whole wheat', false, 'low', array['bread','pasta','baked_goods','sauce_thickener'], array['grain','whole_grain','gluten','wheat','fodmap']),
  ('Rye', array['rye bread','pumpernickel'], true, 'Rye', false, 'low', array['bread','crackers'], array['grain','whole_grain','gluten','fodmap']),
  ('Buckwheat', array['soba','kasha'], true, 'Buckwheat', false, 'low', array['noodles','pancake','porridge'], array['grain','whole_grain','gluten_free']),
  ('Millet', array['millet grain'], true, 'Millet', false, 'low', array['porridge','flatbread'], array['grain','whole_grain','gluten_free']),
  ('Sorghum', array['jowar','milo'], true, 'Sorghum', false, 'low', array['porridge','flour'], array['grain','whole_grain','gluten_free']),
  ('Almond', array['almonds','almond butter','almond meal'], true, 'Almond', false, 'low', array['baked_goods','pesto','milk'], array['nut','tree_nut']),
  ('Walnut', array['walnuts'], true, 'Walnut', false, 'moderate', array['salad','baked_goods','pesto'], array['nut','tree_nut']),
  ('Cashew', array['cashews','cashew butter'], true, 'Cashew', false, 'moderate', array['curry','sauce','stir_fry'], array['nut','tree_nut','fodmap']),
  ('Pistachio', array['pistachios'], true, 'Pistachio', false, 'moderate', array['dessert','baked_goods'], array['nut','tree_nut','fodmap']),
  ('Hazelnut', array['hazelnuts','filbert'], true, 'Hazelnut', false, 'moderate', array['dessert','spread','baked_goods'], array['nut','tree_nut']),
  ('Pecan', array['pecans'], true, 'Pecan', false, 'low', array['pie','salad','baked_goods'], array['nut','tree_nut']),
  ('Brazil nut', array['brazil nuts'], true, 'Brazil nut', false, 'low', array['baked_goods','snack_mix'], array['nut','tree_nut']),
  ('Flaxseed', array['flax','linseed','ground flaxseed'], true, 'Flaxseed', false, 'low', array['smoothie','baked_goods','porridge'], array['seed']),
  ('Chia seed', array['chia','chia seeds'], true, 'Chia seed', false, 'low', array['pudding','smoothie','baked_goods'], array['seed']),
  ('Sesame seed', array['sesame','tahini','til'], true, 'Sesame seed', false, 'moderate', array['tahini','dressing','baked_goods','stir_fry'], array['seed','sesame']),
  ('Sunflower seed', array['sunflower seeds','sunflower butter'], true, 'Sunflower seed', false, 'low', array['salad','baked_goods','snack_mix'], array['seed']),
  ('Pumpkin seed', array['pepitas','pumpkin seeds'], true, 'Pumpkin seed', false, 'low', array['salad','snack_mix','granola'], array['seed']),
  ('Apple', array['apples','green apple','red apple'], true, 'Apple', false, 'low', array['sauce','pie','juice','slaw'], array['fruit','fodmap']),
  ('Banana', array['ripe banana','bananas'], true, 'Banana', false, 'moderate', array['smoothie','baked_goods'], array['fruit']),
  ('Green banana', array['unripe banana','cooking banana','plantain'], true, 'Green banana', false, 'low', array['smoothie','curry'], array['fruit']),
  ('Blueberry', array['blueberries','wild blueberry'], true, 'Blueberry', false, 'low', array['smoothie','muffin','pancake'], array['fruit','berry','blue_purple','polyphenol_rich']),
  ('Strawberry', array['strawberries'], true, 'Strawberry', false, 'moderate', array['smoothie','dessert','jam'], array['fruit','berry','red']),
  ('Raspberry', array['raspberries'], true, 'Raspberry', false, 'high', array['smoothie','dessert','jam'], array['fruit','berry','red','polyphenol_rich']),
  ('Blackberry', array['blackberries'], true, 'Blackberry', false, 'moderate', array['smoothie','dessert','jam'], array['fruit','berry','blue_purple','polyphenol_rich']),
  ('Orange', array['oranges','mandarin','clementine'], true, 'Orange', false, 'moderate', array['juice','salad','dessert'], array['fruit','citrus','orange']),
  ('Lemon', array['lemons','lemon juice'], true, 'Lemon', false, 'high', array['dressing','marinade','dessert','juice'], array['fruit','citrus','yellow']),
  ('Grape', array['grapes','green grape','red grape'], true, 'Grape', false, 'low', array['salad','juice','snack'], array['fruit']),
  ('Concord grape', array['concord grapes','purple grape'], true, 'Concord grape', false, 'low', array['juice','jam'], array['fruit','blue_purple','polyphenol_rich']),
  ('Pomegranate', array['pomegranate seeds','arils'], true, 'Pomegranate', false, 'low', array['salad','juice','garnish'], array['fruit','red','polyphenol_rich']),
  ('Kiwi', array['kiwifruit','kiwis'], true, 'Kiwi', false, 'moderate', array['smoothie','salad','dessert'], array['fruit','green']),
  ('Mango', array['mangoes','mango'], true, 'Mango', false, 'moderate', array['smoothie','salsa','curry'], array['fruit','orange','fodmap']),
  ('Pineapple', array['pineapples','ananas'], true, 'Pineapple', false, 'moderate', array['smoothie','salsa','dessert'], array['fruit','yellow']),
  ('Pear', array['pears','bartlett','bosc'], true, 'Pear', false, 'low', array['salad','dessert','juice'], array['fruit','fodmap']),
  ('Avocado', array['avocados','guacamole'], true, 'Avocado', false, 'high', array['guacamole','salad','toast'], array['fruit','green','fodmap']),
  ('Fig', array['figs','dried fig'], true, 'Fig', false, 'low', array['salad','dessert','jam'], array['fruit','fodmap']),
  ('Cranberry', array['cranberries','dried cranberry'], true, 'Cranberry', false, 'low', array['sauce','juice','baked_goods'], array['fruit','red','polyphenol_rich']),
  ('Date', array['dates','medjool'], true, 'Date', false, 'low', array['energy_ball','dessert','smoothie'], array['fruit','fodmap']),
  ('Basil', array['fresh basil','sweet basil'], true, 'Basil', false, 'low', array['pesto','pasta_sauce','salad'], array['herb_spice','green']),
  ('Parsley', array['flat-leaf parsley','curly parsley'], true, 'Parsley', false, 'low', array['garnish','tabbouleh','sauce'], array['herb_spice','green']),
  ('Cilantro', array['coriander leaf','fresh coriander'], true, 'Cilantro', false, 'low', array['salsa','curry','garnish'], array['herb_spice','green']),
  ('Mint', array['fresh mint','spearmint'], true, 'Mint', false, 'low', array['salad','tea','dessert','chutney'], array['herb_spice','green']),
  ('Rosemary', array['fresh rosemary'], true, 'Rosemary', false, 'low', array['roast','marinade','bread'], array['herb_spice','green']),
  ('Thyme', array['fresh thyme'], true, 'Thyme', false, 'low', array['stock','roast','stew'], array['herb_spice','green']),
  ('Oregano', array['fresh oregano','dried oregano'], true, 'Oregano', false, 'low', array['pizza_sauce','pasta_sauce','marinade'], array['herb_spice','green']),
  ('Cinnamon', array['ground cinnamon','cinnamon stick'], true, 'Cinnamon', false, 'low', array['baked_goods','curry','oatmeal','chai'], array['herb_spice','white_brown']),
  ('Nutmeg', array['ground nutmeg'], true, 'Nutmeg', false, 'low', array['baked_goods','bechamel','curry'], array['herb_spice','white_brown']),
  ('Cumin', array['ground cumin','cumin seed','jeera'], true, 'Cumin', false, 'low', array['curry','chili','spice_blend'], array['herb_spice','white_brown']),
  ('Black pepper', array['peppercorn','ground pepper'], true, 'Black pepper', false, 'moderate', array['almost_any_savory_dish'], array['herb_spice','white_brown']),
  ('Sumac', array['ground sumac'], true, 'Sumac', false, 'low', array['dressing','spice_blend','garnish'], array['herb_spice','red']),
  ('White mushroom', array['button mushroom','cremini','portobello'], true, 'White mushroom', false, 'moderate', array['stir_fry','soup','sauce','pizza_topping'], array['mushroom','white_brown','fodmap']),
  ('Shiitake mushroom', array['shiitake','dried shiitake'], true, 'Shiitake mushroom', false, 'moderate', array['stir_fry','broth','ramen'], array['mushroom','white_brown','fodmap']),
  ('Oyster mushroom', array['oyster mushrooms'], true, 'Oyster mushroom', false, 'moderate', array['stir_fry','soup'], array['mushroom','white_brown']),
  ('Nori', array['seaweed sheet','laver'], true, 'Nori', false, 'moderate', array['sushi','snack','garnish'], array['seaweed']),
  ('Wakame', array['seaweed salad','wakame'], true, 'Wakame', false, 'moderate', array['miso_soup','salad'], array['seaweed']),
  ('Kombu', array['kelp','dashi kelp'], true, 'Kombu', false, 'moderate', array['dashi','broth','bean_cooking'], array['seaweed']),
  ('Tofu', array['bean curd','firm tofu','silken tofu'], true, null, false, 'moderate', array['stir_fry','curry','soup','scramble'], array['soy','legume']),
  ('Green tea', array['matcha','sencha','green tea leaves'], true, null, false, 'moderate', array['latte','smoothie'], array['beverage','polyphenol_rich']),
  ('Yogurt', array['plain yogurt','greek yogurt','curd'], false, null, true, 'moderate', array['smoothie','dressing','dip','marinade'], array['dairy','fermented']),
  ('Kefir', array['milk kefir','kefir drink'], false, null, true, 'high', array['smoothie'], array['dairy','fermented','high_histamine']),
  ('Aged cheese', array['cheddar','parmesan','hard cheese'], false, null, true, 'high', array['pasta','pizza','sauce','gratin'], array['dairy','fermented','high_histamine']),
  ('Sauerkraut', array['fermented cabbage','kraut'], true, null, true, 'high', array['hot_dog_topping','salad'], array['fermented','cruciferous','high_histamine','fodmap']),
  ('Kimchi', array['fermented kimchi','baechu'], true, null, true, 'high', array['stir_fry','rice_bowl','stew'], array['fermented','cruciferous','allium','high_histamine','fodmap']),
  ('Miso', array['miso paste','red miso','white miso'], true, null, true, 'high', array['soup','marinade','dressing'], array['fermented','soy','high_histamine','fodmap']),
  ('Tempeh', array['fermented soy cake'], true, null, true, 'moderate', array['stir_fry','sandwich'], array['fermented','soy']),
  ('Natto', array['fermented soybeans'], true, null, true, 'high', array['rice_bowl'], array['fermented','soy','high_histamine']),
  ('Sourdough bread', array['sourdough','levain'], true, null, true, 'low', array['sandwich','toast'], array['fermented','grain','gluten','wheat']),
  ('Kombucha', array['fermented tea','booch'], true, null, true, 'moderate', '{}'::text[], array['fermented','beverage','polyphenol_rich'])
) as v(canonical_name, aliases, is_plant, plant_name, is_fermented, histamine_level, common_hidden_in, categories)
left join plants p on p.name = v.plant_name
on conflict (canonical_name) do update set
  aliases = excluded.aliases,
  is_plant = excluded.is_plant,
  plant_id = excluded.plant_id,
  is_fermented = excluded.is_fermented,
  histamine_level = excluded.histamine_level,
  common_hidden_in = excluded.common_hidden_in,
  categories = excluded.categories;

-- ---- food_fibers — ON CONFLICT (food_id,fiber_id); Fence 4 grams -----
insert into food_fibers (food_id, fiber_id, relative_amount, est_grams_per_serving)
select fo.id, fi.id, v.relative_amount::amount_tier, v.est_grams
from (values
  ('Garlic', 'inulin', 'primary', 2.0),
  ('Garlic', 'fos', 'moderate', 1.0),
  ('Onion', 'inulin', 'moderate', 1.2),
  ('Onion', 'fos', 'moderate', 1.0),
  ('Leek', 'inulin', 'moderate', 1.5),
  ('Leek', 'fos', 'minor', 0.5),
  ('Shallot', 'inulin', 'moderate', 1.3),
  ('Asparagus', 'inulin', 'moderate', 1.5),
  ('Asparagus', 'fos', 'minor', 0.6),
  ('Jerusalem artichoke', 'inulin', 'primary', 6.0),
  ('Chicory root', 'inulin', 'primary', 10.0),
  ('Banana', 'fos', 'minor', 0.5),
  ('Whole wheat', 'arabinoxylan', 'primary', 2.5),
  ('Whole wheat', 'fos', 'minor', 0.5),
  ('Rye', 'arabinoxylan', 'primary', 3.0),
  ('Barley', 'arabinoxylan', 'moderate', 1.5),
  ('Barley', 'beta_glucan', 'primary', 2.5),
  ('Oats', 'beta_glucan', 'primary', 3.0),
  ('Oats', 'arabinoxylan', 'minor', 0.8),
  ('Oats', 'rs2', 'minor', 0.5),
  ('White mushroom', 'beta_glucan', 'moderate', 1.0),
  ('Shiitake mushroom', 'beta_glucan', 'moderate', 1.2),
  ('Oyster mushroom', 'beta_glucan', 'moderate', 1.0),
  ('Chickpea', 'gos', 'primary', 2.5),
  ('Lentil', 'gos', 'moderate', 1.8),
  ('Black bean', 'gos', 'primary', 2.2),
  ('Kidney bean', 'gos', 'primary', 2.0),
  ('White bean', 'gos', 'moderate', 1.8),
  ('Soybean', 'gos', 'moderate', 1.5),
  ('Green pea', 'gos', 'moderate', 1.2),
  ('Peanut', 'gos', 'minor', 0.6),
  ('Green banana', 'rs2', 'primary', 4.5),
  ('Potato', 'rs3', 'moderate', 2.0),
  ('Brown rice', 'rs3', 'moderate', 1.5),
  ('Apple', 'pectin', 'primary', 1.5),
  ('Carrot', 'pectin', 'moderate', 1.2),
  ('Orange', 'pectin', 'moderate', 1.5),
  ('Lemon', 'pectin', 'moderate', 1.0),
  ('Pear', 'pectin', 'moderate', 1.4),
  ('Beet', 'pectin', 'minor', 0.7),
  ('Flaxseed', 'mucilage', 'primary', 3.0),
  ('Chia seed', 'mucilage', 'primary', 3.5),
  ('Okra', 'mucilage', 'primary', 2.0),
  ('Sorghum', 'arabinoxylan', 'minor', 0.8),
  ('Millet', 'arabinoxylan', 'minor', 0.7)
) as v(food, fiber, relative_amount, est_grams)
join foods fo on fo.canonical_name = v.food
join fibers fi on fi.name = v.fiber
on conflict (food_id, fiber_id) do update set
  relative_amount = excluded.relative_amount,
  est_grams_per_serving = excluded.est_grams_per_serving;

-- ---- food_colors — ON CONFLICT (food_id,color_id) do nothing (pk-only)
insert into food_colors (food_id, color_id)
select fo.id, v.color::color_name
from (values
  ('Garlic', 'white_brown'),
  ('Onion', 'white_brown'),
  ('Leek', 'white_brown'),
  ('Shallot', 'white_brown'),
  ('Spring onion', 'green'),
  ('Chives', 'green'),
  ('Broccoli', 'green'),
  ('Cauliflower', 'white_brown'),
  ('Cabbage', 'green'),
  ('Kale', 'green'),
  ('Brussels sprouts', 'green'),
  ('Bok choy', 'green'),
  ('Arugula', 'green'),
  ('Radish', 'red'),
  ('Turnip', 'white_brown'),
  ('Watercress', 'green'),
  ('Spinach', 'green'),
  ('Romaine lettuce', 'green'),
  ('Swiss chard', 'green'),
  ('Collard greens', 'green'),
  ('Carrot', 'orange'),
  ('Beet', 'red'),
  ('Sweet potato', 'orange'),
  ('Potato', 'white_brown'),
  ('Parsnip', 'white_brown'),
  ('Ginger', 'white_brown'),
  ('Turmeric', 'yellow'),
  ('Jerusalem artichoke', 'white_brown'),
  ('Chicory root', 'white_brown'),
  ('Pumpkin', 'orange'),
  ('Butternut squash', 'orange'),
  ('Zucchini', 'green'),
  ('Cucumber', 'green'),
  ('Tomato', 'red'),
  ('Bell pepper', 'red'),
  ('Eggplant', 'blue_purple'),
  ('Chili pepper', 'red'),
  ('Asparagus', 'green'),
  ('Celery', 'green'),
  ('Fennel', 'white_brown'),
  ('Artichoke', 'green'),
  ('Okra', 'green'),
  ('Green pea', 'green'),
  ('Corn', 'yellow'),
  ('Chickpea', 'white_brown'),
  ('Lentil', 'white_brown'),
  ('Black bean', 'blue_purple'),
  ('Kidney bean', 'red'),
  ('White bean', 'white_brown'),
  ('Soybean', 'green'),
  ('Peanut', 'white_brown'),
  ('Oats', 'white_brown'),
  ('Barley', 'white_brown'),
  ('Brown rice', 'white_brown'),
  ('Quinoa', 'white_brown'),
  ('Whole wheat', 'white_brown'),
  ('Rye', 'white_brown'),
  ('Buckwheat', 'white_brown'),
  ('Millet', 'yellow'),
  ('Sorghum', 'white_brown'),
  ('Almond', 'white_brown'),
  ('Walnut', 'white_brown'),
  ('Cashew', 'white_brown'),
  ('Pistachio', 'green'),
  ('Hazelnut', 'white_brown'),
  ('Pecan', 'white_brown'),
  ('Brazil nut', 'white_brown'),
  ('Flaxseed', 'white_brown'),
  ('Chia seed', 'white_brown'),
  ('Sesame seed', 'white_brown'),
  ('Sunflower seed', 'white_brown'),
  ('Pumpkin seed', 'green'),
  ('Apple', 'red'),
  ('Apple', 'green'),
  ('Banana', 'yellow'),
  ('Green banana', 'green'),
  ('Blueberry', 'blue_purple'),
  ('Strawberry', 'red'),
  ('Raspberry', 'red'),
  ('Blackberry', 'blue_purple'),
  ('Orange', 'orange'),
  ('Lemon', 'yellow'),
  ('Grape', 'green'),
  ('Concord grape', 'blue_purple'),
  ('Pomegranate', 'red'),
  ('Kiwi', 'green'),
  ('Mango', 'orange'),
  ('Pineapple', 'yellow'),
  ('Pear', 'green'),
  ('Avocado', 'green'),
  ('Fig', 'blue_purple'),
  ('Cranberry', 'red'),
  ('Date', 'white_brown'),
  ('Basil', 'green'),
  ('Parsley', 'green'),
  ('Cilantro', 'green'),
  ('Mint', 'green'),
  ('Rosemary', 'green'),
  ('Thyme', 'green'),
  ('Oregano', 'green'),
  ('Cinnamon', 'white_brown'),
  ('Nutmeg', 'white_brown'),
  ('Cumin', 'white_brown'),
  ('Black pepper', 'white_brown'),
  ('Sumac', 'red'),
  ('White mushroom', 'white_brown'),
  ('Shiitake mushroom', 'white_brown'),
  ('Oyster mushroom', 'white_brown'),
  ('Nori', 'green'),
  ('Wakame', 'green'),
  ('Kombu', 'green'),
  ('Tofu', 'white_brown'),
  ('Green tea', 'green'),
  ('Yogurt', 'white_brown'),
  ('Kefir', 'white_brown'),
  ('Aged cheese', 'yellow'),
  ('Sauerkraut', 'white_brown'),
  ('Kimchi', 'red'),
  ('Miso', 'white_brown'),
  ('Tempeh', 'white_brown'),
  ('Natto', 'white_brown'),
  ('Sourdough bread', 'white_brown'),
  ('Kombucha', 'white_brown')
) as v(food, color)
join foods fo on fo.canonical_name = v.food
on conflict (food_id, color_id) do nothing;

-- ---- food_phytochemicals — ON CONFLICT (pk) do nothing (pk-only) -----
insert into food_phytochemicals (food_id, phytochemical_id)
select fo.id, ph.id
from (values
  ('Garlic', 'allicin'),
  ('Garlic', 's_allyl_cysteine'),
  ('Onion', 'quercetin'),
  ('Onion', 's_allyl_cysteine'),
  ('Leek', 'kaempferol'),
  ('Chives', 'kaempferol'),
  ('Broccoli', 'sulforaphane'),
  ('Broccoli', 'glucosinolate'),
  ('Broccoli', 'lutein'),
  ('Cauliflower', 'glucosinolate'),
  ('Cabbage', 'glucosinolate'),
  ('Kale', 'sulforaphane'),
  ('Kale', 'lutein'),
  ('Kale', 'kaempferol'),
  ('Brussels sprouts', 'glucosinolate'),
  ('Brussels sprouts', 'sulforaphane'),
  ('Bok choy', 'glucosinolate'),
  ('Arugula', 'glucosinolate'),
  ('Radish', 'glucosinolate'),
  ('Watercress', 'glucosinolate'),
  ('Spinach', 'lutein'),
  ('Spinach', 'zeaxanthin'),
  ('Spinach', 'chlorophyll'),
  ('Romaine lettuce', 'lutein'),
  ('Swiss chard', 'lutein'),
  ('Swiss chard', 'betanin'),
  ('Collard greens', 'lutein'),
  ('Collard greens', 'chlorophyll'),
  ('Carrot', 'beta_carotene'),
  ('Carrot', 'alpha_carotene'),
  ('Beet', 'betanin'),
  ('Sweet potato', 'beta_carotene'),
  ('Turmeric', 'curcumin'),
  ('Pumpkin', 'beta_carotene'),
  ('Butternut squash', 'beta_carotene'),
  ('Tomato', 'lycopene'),
  ('Bell pepper', 'beta_cryptoxanthin'),
  ('Bell pepper', 'capsaicin'),
  ('Eggplant', 'anthocyanin'),
  ('Chili pepper', 'capsaicin'),
  ('Parsley', 'kaempferol'),
  ('Basil', 'chlorophyll'),
  ('Rosemary', 'carnosic_acid'),
  ('Oregano', 'carnosic_acid'),
  ('Black pepper', 'piperine'),
  ('Sumac', 'ellagic_acid'),
  ('Corn', 'zeaxanthin'),
  ('Apple', 'quercetin'),
  ('Apple', 'chlorogenic_acid'),
  ('Blueberry', 'anthocyanin'),
  ('Strawberry', 'ellagic_acid'),
  ('Strawberry', 'anthocyanin'),
  ('Raspberry', 'ellagic_acid'),
  ('Raspberry', 'anthocyanin'),
  ('Blackberry', 'anthocyanin'),
  ('Blackberry', 'ellagic_acid'),
  ('Cranberry', 'anthocyanin'),
  ('Pomegranate', 'punicalagin'),
  ('Pomegranate', 'ellagic_acid'),
  ('Concord grape', 'resveratrol'),
  ('Concord grape', 'anthocyanin'),
  ('Grape', 'resveratrol'),
  ('Orange', 'hesperidin'),
  ('Orange', 'beta_cryptoxanthin'),
  ('Lemon', 'hesperidin'),
  ('Mango', 'beta_carotene'),
  ('Pineapple', 'naringenin'),
  ('Fig', 'anthocyanin'),
  ('Avocado', 'beta_sitosterol'),
  ('Walnut', 'ellagic_acid'),
  ('Almond', 'beta_sitosterol'),
  ('Flaxseed', 'secoisolariciresinol'),
  ('Sesame seed', 'secoisolariciresinol'),
  ('Soybean', 'genistein'),
  ('Tofu', 'genistein'),
  ('Tempeh', 'genistein'),
  ('Miso', 'genistein'),
  ('Green tea', 'epigallocatechin_gallate'),
  ('Green tea', 'catechin'),
  ('Kombucha', 'catechin'),
  ('Oats', 'beta_sitosterol'),
  ('Sunflower seed', 'beta_sitosterol'),
  ('Pistachio', 'lutein'),
  ('Cinnamon', 'chlorogenic_acid')
) as v(food, phyto)
join foods fo on fo.canonical_name = v.food
join phytochemicals ph on ph.name = v.phyto
on conflict (food_id, phytochemical_id) do nothing;

-- ---- food_guild_feeds — ON CONFLICT (food_id,guild_id) do update -----
insert into food_guild_feeds (food_id, guild_id, relevance)
select fo.id, g.id, v.relevance::amount_tier
from (values
  ('Garlic', 'base_layer', 'primary'),
  ('Onion', 'base_layer', 'primary'),
  ('Leek', 'base_layer', 'moderate'),
  ('Shallot', 'base_layer', 'moderate'),
  ('Spring onion', 'base_layer', 'minor'),
  ('Asparagus', 'base_layer', 'moderate'),
  ('Jerusalem artichoke', 'base_layer', 'primary'),
  ('Chicory root', 'base_layer', 'primary'),
  ('Chickpea', 'base_layer', 'moderate'),
  ('Lentil', 'base_layer', 'moderate'),
  ('Black bean', 'base_layer', 'moderate'),
  ('Soybean', 'base_layer', 'moderate'),
  ('Whole wheat', 'base_layer', 'minor'),
  ('Garlic', 'recycling_engine', 'minor'),
  ('Chicory root', 'recycling_engine', 'minor'),
  ('Onion', 'recycling_engine', 'minor'),
  ('Oats', 'anti_inflammatory_arsenal', 'primary'),
  ('Green banana', 'anti_inflammatory_arsenal', 'moderate'),
  ('Potato', 'anti_inflammatory_arsenal', 'moderate'),
  ('Brown rice', 'anti_inflammatory_arsenal', 'moderate'),
  ('Apple', 'anti_inflammatory_arsenal', 'primary'),
  ('Carrot', 'anti_inflammatory_arsenal', 'moderate'),
  ('Pear', 'anti_inflammatory_arsenal', 'moderate'),
  ('Orange', 'anti_inflammatory_arsenal', 'minor'),
  ('Flaxseed', 'anti_inflammatory_arsenal', 'moderate'),
  ('Chia seed', 'anti_inflammatory_arsenal', 'moderate'),
  ('Okra', 'anti_inflammatory_arsenal', 'moderate'),
  ('Oats', 'appetite_crew', 'primary'),
  ('Barley', 'appetite_crew', 'primary'),
  ('Whole wheat', 'appetite_crew', 'moderate'),
  ('Rye', 'appetite_crew', 'moderate'),
  ('White mushroom', 'appetite_crew', 'moderate'),
  ('Shiitake mushroom', 'appetite_crew', 'moderate'),
  ('Oyster mushroom', 'appetite_crew', 'moderate'),
  ('Green banana', 'locksmith', 'primary'),
  ('Potato', 'locksmith', 'moderate'),
  ('Brown rice', 'locksmith', 'moderate'),
  ('Oats', 'locksmith', 'minor'),
  ('Lentil', 'locksmith', 'minor'),
  ('Cranberry', 'knights_of_the_wall', 'primary'),
  ('Pomegranate', 'knights_of_the_wall', 'primary'),
  ('Green tea', 'knights_of_the_wall', 'primary'),
  ('Concord grape', 'knights_of_the_wall', 'primary'),
  ('Blueberry', 'knights_of_the_wall', 'moderate'),
  ('Raspberry', 'knights_of_the_wall', 'moderate'),
  ('Blackberry', 'knights_of_the_wall', 'moderate'),
  ('Spinach', 'vitamin_lab', 'moderate'),
  ('Kale', 'vitamin_lab', 'moderate'),
  ('Broccoli', 'vitamin_lab', 'moderate'),
  ('Romaine lettuce', 'vitamin_lab', 'moderate'),
  ('Parsley', 'vitamin_lab', 'minor'),
  ('Swiss chard', 'vitamin_lab', 'minor'),
  ('Asparagus', 'vitamin_lab', 'minor'),
  ('Beet', 'vitamin_lab', 'minor'),
  ('Natto', 'vitamin_lab', 'moderate'),
  ('Oats', 'mood_regulators', 'moderate'),
  ('Pumpkin seed', 'mood_regulators', 'moderate'),
  ('Sunflower seed', 'mood_regulators', 'moderate'),
  ('Sesame seed', 'mood_regulators', 'moderate'),
  ('Soybean', 'mood_regulators', 'moderate'),
  ('Tofu', 'mood_regulators', 'moderate'),
  ('Soybean', 'estrogen_regulators', 'primary'),
  ('Tempeh', 'estrogen_regulators', 'primary'),
  ('Natto', 'estrogen_regulators', 'primary'),
  ('Tofu', 'estrogen_regulators', 'moderate'),
  ('Miso', 'estrogen_regulators', 'moderate'),
  ('Pomegranate', 'mitochondria_boosters', 'primary'),
  ('Walnut', 'mitochondria_boosters', 'primary'),
  ('Raspberry', 'mitochondria_boosters', 'moderate'),
  ('Strawberry', 'mitochondria_boosters', 'moderate'),
  ('Blackberry', 'mitochondria_boosters', 'moderate'),
  ('Blueberry', 'mitochondria_boosters', 'minor'),
  ('Flaxseed', 'tumor_preventors', 'primary'),
  ('Sesame seed', 'tumor_preventors', 'moderate'),
  ('Rye', 'tumor_preventors', 'moderate'),
  ('Spinach', 'stone_breakers', 'moderate'),
  ('Beet', 'stone_breakers', 'moderate'),
  ('Swiss chard', 'stone_breakers', 'moderate'),
  ('Almond', 'stone_breakers', 'minor')
) as v(food, guild, relevance)
join foods fo on fo.canonical_name = v.food
join guilds g on g.internal_name = v.guild
on conflict (food_id, guild_id) do update set relevance = excluded.relevance;

-- ---- fodmap_profiles — ON CONFLICT (food_id) do update; FENCE 4 ------
insert into fodmap_profiles (food_id, fructan_level, gos_level, lactose_level, fructose_level, polyol_level, serving_size_desc, safety)
select fo.id, v.fructan::fodmap_level, v.gos::fodmap_level, v.lactose::fodmap_level, v.fructose::fodmap_level, v.polyol::fodmap_level, v.serving, v.safety::fodmap_safety
from (values
  ('Garlic', 'high', 'none', 'none', 'none', 'none', '2-3 cloves', 'red'),
  ('Onion', 'high', 'none', 'none', 'none', 'none', '1/4 cup chopped', 'red'),
  ('Leek', 'high', 'none', 'none', 'none', 'none', '1/2 leek bulb', 'red'),
  ('Shallot', 'high', 'none', 'none', 'none', 'none', '1 small shallot', 'red'),
  ('Chicory root', 'high', 'none', 'none', 'none', 'none', '1 tsp inulin powder', 'red'),
  ('Jerusalem artichoke', 'high', 'none', 'none', 'none', 'none', '1/2 cup', 'red'),
  ('Asparagus', 'moderate', 'none', 'none', 'high', 'none', '2 spears', 'red'),
  ('Whole wheat', 'moderate', 'none', 'none', 'none', 'none', '1 slice bread', 'yellow'),
  ('Rye', 'high', 'none', 'none', 'none', 'none', '2 slices bread', 'red'),
  ('Barley', 'moderate', 'moderate', 'none', 'none', 'none', '1/2 cup cooked', 'red'),
  ('Chickpea', 'none', 'high', 'none', 'none', 'none', '1/4 cup canned, rinsed', 'red'),
  ('Lentil', 'none', 'moderate', 'none', 'none', 'none', '1/4 cup boiled', 'yellow'),
  ('Black bean', 'none', 'high', 'none', 'none', 'none', '1/2 cup', 'red'),
  ('Kidney bean', 'none', 'high', 'none', 'none', 'none', '1/2 cup', 'red'),
  ('White bean', 'none', 'high', 'none', 'none', 'none', '1/2 cup', 'red'),
  ('Soybean', 'none', 'low', 'none', 'none', 'none', '1/2 cup edamame', 'green'),
  ('Green pea', 'moderate', 'none', 'none', 'none', 'none', '1/2 cup', 'yellow'),
  ('Apple', 'none', 'none', 'none', 'high', 'high', '1 medium', 'red'),
  ('Pear', 'none', 'none', 'none', 'high', 'high', '1 medium', 'red'),
  ('Mango', 'none', 'none', 'none', 'high', 'none', '1/2 fruit', 'red'),
  ('Avocado', 'none', 'none', 'none', 'none', 'moderate', '1/4 fruit', 'yellow'),
  ('Fig', 'moderate', 'none', 'none', 'moderate', 'none', '1 fresh fig', 'red'),
  ('Date', 'moderate', 'none', 'none', 'moderate', 'none', '2 dates', 'red'),
  ('Cashew', 'moderate', 'high', 'none', 'none', 'none', '10 nuts', 'red'),
  ('Pistachio', 'high', 'high', 'none', 'none', 'none', '10 nuts', 'red'),
  ('Butternut squash', 'none', 'none', 'none', 'none', 'moderate', '1/2 cup', 'yellow'),
  ('White mushroom', 'none', 'none', 'none', 'none', 'high', '1/2 cup', 'red'),
  ('Shiitake mushroom', 'high', 'none', 'none', 'none', 'high', '1/2 cup', 'red'),
  ('Cauliflower', 'none', 'none', 'none', 'none', 'high', '1/2 cup', 'red'),
  ('Broccoli', 'moderate', 'none', 'none', 'none', 'none', '3/4 cup', 'yellow'),
  ('Brussels sprouts', 'moderate', 'none', 'none', 'none', 'none', '1/2 cup', 'yellow'),
  ('Okra', 'none', 'moderate', 'none', 'none', 'none', '1/2 cup', 'yellow'),
  ('Sauerkraut', 'moderate', 'none', 'none', 'none', 'moderate', '2 tbsp', 'yellow'),
  ('Kimchi', 'moderate', 'none', 'none', 'none', 'none', '2 tbsp', 'yellow'),
  ('Miso', 'moderate', 'moderate', 'none', 'none', 'none', '1 tbsp paste', 'yellow'),
  ('Carrot', 'none', 'none', 'none', 'none', 'none', '1 medium', 'green'),
  ('Spinach', 'none', 'none', 'none', 'none', 'none', '1 cup', 'green'),
  ('Cucumber', 'none', 'none', 'none', 'none', 'none', '1/2 cup', 'green'),
  ('Tomato', 'none', 'none', 'none', 'low', 'none', '1 medium', 'green'),
  ('Bell pepper', 'none', 'none', 'none', 'low', 'none', '1/2 cup', 'green'),
  ('Zucchini', 'low', 'none', 'none', 'none', 'none', '1/2 cup', 'green'),
  ('Eggplant', 'none', 'none', 'none', 'none', 'none', '1 cup', 'green'),
  ('Potato', 'none', 'none', 'none', 'none', 'none', '1 medium', 'green'),
  ('Brown rice', 'none', 'none', 'none', 'none', 'none', '1 cup cooked', 'green'),
  ('Quinoa', 'none', 'none', 'none', 'none', 'none', '1 cup cooked', 'green'),
  ('Oats', 'low', 'none', 'none', 'none', 'none', '1/2 cup dry', 'green'),
  ('Kale', 'none', 'none', 'none', 'none', 'none', '1 cup', 'green'),
  ('Blueberry', 'none', 'none', 'none', 'low', 'none', '20 berries', 'green'),
  ('Strawberry', 'none', 'none', 'none', 'low', 'none', '10 berries', 'green'),
  ('Raspberry', 'none', 'none', 'none', 'none', 'none', '10 berries', 'green'),
  ('Orange', 'none', 'none', 'none', 'none', 'none', '1 medium', 'green'),
  ('Banana', 'none', 'none', 'none', 'low', 'none', '1 medium firm', 'green'),
  ('Green banana', 'none', 'none', 'none', 'none', 'none', '1 medium', 'green'),
  ('Tofu', 'none', 'none', 'none', 'none', 'none', '3/4 cup firm', 'green'),
  ('Tempeh', 'none', 'none', 'none', 'none', 'none', '1/2 cup', 'green'),
  ('Yogurt', 'none', 'none', 'high', 'none', 'none', '1/2 cup', 'red'),
  ('Kefir', 'none', 'none', 'high', 'none', 'none', '1 cup', 'red'),
  ('Aged cheese', 'none', 'none', 'low', 'none', 'none', '40 g', 'green')
) as v(food, fructan, gos, lactose, fructose, polyol, serving, safety)
join foods fo on fo.canonical_name = v.food
on conflict (food_id) do update set
  fructan_level = excluded.fructan_level,
  gos_level = excluded.gos_level,
  lactose_level = excluded.lactose_level,
  fructose_level = excluded.fructose_level,
  polyol_level = excluded.polyol_level,
  serving_size_desc = excluded.serving_size_desc,
  safety = excluded.safety;

-- ---- curiosity_facts — no natural key in schema; delete+insert (idempotent,
--      supersedes demo rows). Curated, not runtime-generated (CLAUDE.md #9).
delete from curiosity_facts;
insert into curiosity_facts (fact_text, topic_tags, confidence_tag) values
  ('Cooling cooked rice or potatoes turns some of their starch into RS3, a resistant starch your butyrate-producing crews love.', array['resistant_starch','rs3','butyrate'], 'solid'),
  ('The same fructans that feed your Base Layer bifidobacteria are also classic IBS triggers. One molecule, two lenses.', array['inulin','fructan','fodmap'], 'solid'),
  ('Your gut bacteria make most of your body''s butyrate, the short-chain fatty acid that fuels the cells lining your colon.', array['butyrate','short_chain_fatty_acids'], 'solid'),
  ('Aiming for 30 different plants a week is linked with a more diverse gut microbiome than counting servings alone.', array['diversity','30_plants'], 'maturing'),
  ('Chicory root is one of the richest natural sources of inulin, which is why it is often added to foods as a prebiotic fiber.', array['inulin','chicory','prebiotic'], 'solid'),
  ('Mushrooms are not plants but they still count toward your weekly diversity, and they carry beta-glucan fiber that feeds the Appetite Crew.', array['beta_glucan','mushrooms','diversity'], 'solid'),
  ('Oats and barley share a soluble fiber called beta-glucan that is well studied for helping lower cholesterol.', array['beta_glucan','oats','cholesterol'], 'solid'),
  ('Anthocyanins, the deep blue-purple pigments in blueberries and blackberries, reach your colon largely intact and feed barrier-keeping microbes.', array['anthocyanin','polyphenol','blue_purple'], 'maturing'),
  ('Only about one in three people carry the gut bacteria that turn soy isoflavones into equol, a trait you can only confirm with a urine test.', array['equol','soy','metabotype'], 'emerging'),
  ('Whether your microbes make urolithin A from pomegranates and walnuts depends on your personal microbiome, sorted into metabotypes A, B, and 0.', array['urolithin','pomegranate','metabotype'], 'emerging'),
  ('Arabinoxylan, the main fiber in whole wheat and rye, is one of the most overlooked prebiotics in a typical diet.', array['arabinoxylan','whole_grains','prebiotic'], 'solid'),
  ('Ruminococcus bromii, nicknamed the keystone for resistant starch, cracks open starch granules so other microbes can feed too.', array['resistant_starch','keystone','locksmith'], 'solid'),
  ('Sulfur-rich gas has a distinct rotten-egg smell, which is why odor is one of the most useful clues your gut gives you.', array['gas_odor','sulfur','survive'], 'maturing'),
  ('Akkermansia muciniphila lives in your gut''s mucus layer and tends to be more abundant in people eating lots of polyphenol-rich foods.', array['akkermansia','polyphenol','mucus_barrier'], 'maturing'),
  ('Flax and sesame are top sources of plant lignans, which gut bacteria convert into enterolignans.', array['lignan','flax','sesame'], 'associational'),
  ('Green bananas are rich in resistant starch, but as they ripen that starch turns to sugar, which is the classic resistant-starch trade-off.', array['resistant_starch','green_banana','ripening'], 'solid'),
  ('Fermented foods like kimchi and sauerkraut add live microbes, while prebiotic fibers feed the microbes you already have.', array['fermented','probiotic','prebiotic'], 'solid'),
  ('Eating across more color groups is a simple proxy for eating a wider range of polyphenols and carotenoids.', array['rainbow','polyphenol','carotenoid'], 'maturing'),
  ('Garlic loses much of its allicin when cooked, so crushing it and resting it for ten minutes before heating helps preserve more.', array['allicin','garlic','organosulfur'], 'maturing'),
  ('Psyllium husk is barely fermented, so it bulks and softens stool mechanically rather than feeding your microbes much.', array['psyllium','mechanical_fiber'], 'solid'),
  ('Lentils and beans carry GOS, a fiber that is a top prebiotic and, for some people, a top source of gas.', array['gos','legumes','fodmap'], 'solid'),
  ('Your weekly plant count resets, but every unique plant you have ever logged stays in your lifetime collection.', array['gamification','plant_pokedex','diversity'], 'solid');

-- ---- success_stories — delete+insert (idempotent). Truthful + representative;
--      no cherry-picked medical claims (SPEC §2). verified=false until real quote.
delete from success_stories;
insert into success_stories (text, attribution, verified) values
  ('Eating across more colors each week made hitting 30 plants feel like collecting, not a chore.', 'Thrive user (representative)', false),
  ('Going back to basics for a couple of weeks and then adding foods back one at a time finally helped me see which ones actually bothered me.', 'Survive user (representative)', false),
  ('I never knew how few different plants I was eating until the weekly count showed me. Now I hit thirty most weeks.', 'Thrive user (representative)', false),
  ('Tracking the smell of my gas felt silly at first, but it turned out to be the clue that helped me spot my pattern.', 'Survive user (representative)', false),
  ('The garden blooming when I kept feeding the same crews made the science click in a way a chart never did.', 'Thrive user (representative)', false),
  ('Reintroducing onion and garlic slowly, instead of cutting them forever, took the fear out of eating again.', 'Survive user (representative)', false);
